/**
 * FASE 1 — MANIFESTO DA ARQUITETURA DA NINA (somente descrição).
 *
 * Este arquivo NÃO executa nada do fluxo da Nina e NÃO duplica regra de
 * negócio. Ele apenas descreve, de forma estruturada, componentes que já
 * existem no backend (arquivo + função reais), para que uma interface futura
 * possa desenhar e auditar a arquitetura.
 *
 * Regras de manutenção:
 *  - todo node deve apontar para arquivo/função que existem no repositório;
 *  - toda conexão deve representar um caminho realmente possível no código;
 *  - nada aqui pode ser importado pelo fluxo de execução da Nina.
 */

export const CATEGORIAS_ARQUITETURA = [
  "ENTRADA",
  "PROCESSAMENTO",
  "CONTEXTO",
  "MEMORIA",
  "INSTRUCOES",
  "CONHECIMENTO",
  "IA",
  "TOOLS",
  "VALIDACAO",
  "SAIDA",
  "OBSERVABILIDADE",
  "ERRO_FALLBACK",
] as const;

export type CategoriaArquitetura = (typeof CATEGORIAS_ARQUITETURA)[number];

export type NodeArquitetura = {
  id: string;
  nome: string;
  categoria: CategoriaArquitetura;
  descricao: string;
  /** Caminho relativo à raiz do projeto. */
  arquivo?: string;
  /** Nome de função/const exportada ou interna existente no arquivo. */
  funcao?: string;
  /** Serviço externo ou interno acionado, quando houver. */
  servico?: string;
  entrada: string;
  saida: string;
  anteriores: string[];
  seguintes: string[];
  /** Tabelas do banco lidas ou gravadas por este componente. */
  tabelas?: string[];
  /** Erros reais que este ponto pode produzir ou tratar. */
  erros: string[];
};

export const NODES_ARQUITETURA: NodeArquitetura[] = [
  // ───────────────────────── ENTRADA ─────────────────────────
  {
    id: "message.inbound",
    nome: "Webhook WhatsApp (entrada)",
    categoria: "ENTRADA",
    descricao:
      "Rota pública que recebe GET de verificação e POST de eventos da WhatsApp Cloud API por clínica.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "Route",
    servico: "Meta WhatsApp Cloud API",
    entrada: "Requisição HTTP da Meta",
    saida: "Payload do evento",
    anteriores: [],
    seguintes: ["message.log_raw"],
    tabelas: ["whatsapp_configs"],
    erros: ["clínica inexistente", "configuração ausente", "payload sem mensagem"],
  },
  {
    id: "message.log_raw",
    nome: "Log bruto do webhook",
    categoria: "OBSERVABILIDADE",
    descricao: "Registra cabeçalhos, corpo e resultado do evento antes de qualquer processamento.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "registrarLogWebhook",
    entrada: "Requisição bruta",
    saida: "Identificador do log",
    anteriores: ["message.inbound"],
    seguintes: ["message.validate"],
    tabelas: ["whatsapp_webhook_logs"],
    erros: ["falha ao gravar log (ignorada, não interrompe o fluxo)"],
  },
  {
    id: "message.validate",
    nome: "Validação de assinatura",
    categoria: "VALIDACAO",
    descricao:
      "Confere a assinatura HMAC-SHA256 do corpo com o app secret; sem assinatura válida o evento é descartado.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "verifySignature",
    entrada: "Corpo bruto + cabeçalho de assinatura",
    saida: "Booleano de autenticidade",
    anteriores: ["message.log_raw"],
    seguintes: ["message.deduplicate", "status.update"],
    erros: ["assinatura inválida", "app secret ausente"],
  },
  {
    id: "status.update",
    nome: "Atualização de status de envio",
    categoria: "OBSERVABILIDADE",
    descricao: "Trata eventos de status (enviado, entregue, lido, falha) das mensagens de saída.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "registrarStatusWhatsapp",
    entrada: "Evento de status da Meta",
    saida: "Mensagem de saída atualizada",
    anteriores: ["message.validate"],
    seguintes: [],
    tabelas: ["whatsapp_mensagens"],
    erros: ["mensagem não encontrada pelo identificador da Meta"],
  },
  {
    id: "message.deduplicate",
    nome: "Deduplicação e persistência da entrada",
    categoria: "PROCESSAMENTO",
    descricao:
      "Grava a mensagem recebida; o índice único do identificador da Meta impede processar o mesmo evento duas vezes.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNina",
    entrada: "Evento validado",
    saida: "Mensagem persistida ou descarte por duplicidade",
    anteriores: ["message.validate"],
    seguintes: ["conversation.ensure"],
    tabelas: ["whatsapp_mensagens"],
    erros: ["duplicidade (descartada)", "falha de gravação"],
  },
  {
    id: "conversation.ensure",
    nome: "Conversa e identidade do contato",
    categoria: "PROCESSAMENTO",
    descricao:
      "Abre ou recupera a conversa do número e carrega o estado de identificação do paciente.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "carregarEstadoIdentidade",
    entrada: "Telefone e clínica",
    saida: "Estado da conversa e da identidade",
    anteriores: ["message.deduplicate"],
    seguintes: ["conversation.reopen", "routing.decide"],
    tabelas: ["atend_conversas", "pacientes"],
    erros: ["conversa não localizada", "falha ao criar conversa"],
  },
  {
    id: "conversation.reopen",
    nome: "Reabertura por mensagem do paciente",
    categoria: "PROCESSAMENTO",
    descricao: "Conversa encerrada volta a ficar ativa quando o paciente escreve de novo.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "reabrirConversaPorMensagemPaciente",
    entrada: "Conversa encerrada + nova mensagem",
    saida: "Conversa reaberta e evento registrado",
    anteriores: ["conversation.ensure"],
    seguintes: ["routing.decide"],
    tabelas: ["atend_conversas", "atend_conversa_eventos"],
    erros: ["falha ao atualizar estado da conversa"],
  },
  {
    id: "routing.decide",
    nome: "Decisão Nina ou humano",
    categoria: "PROCESSAMENTO",
    descricao:
      "Verifica dono da conversa, IA habilitada e status para decidir se a Nina pode responder.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "ninaPodeResponder",
    entrada: "Estado da conversa",
    saida: "Autorização ou bloqueio da resposta automática",
    anteriores: ["conversation.ensure", "conversation.reopen"],
    seguintes: ["session.resolve", "handoff.queue"],
    tabelas: ["atend_conversas"],
    erros: ["estado inconsistente da conversa"],
  },

  // ───────────────────────── CONTEXTO E MEMÓRIA ─────────────────────────
  {
    id: "session.resolve",
    nome: "Sessão da conversa",
    categoria: "MEMORIA",
    descricao: "Resolve a sessão vigente por tempo de inatividade e persiste o estado atualizado.",
    arquivo: "src/lib/nina/sessao.server.ts",
    funcao: "resolverSessao",
    entrada: "Conversa e horário da mensagem",
    saida: "Sessão vigente ou nova",
    anteriores: ["routing.decide"],
    seguintes: ["context.load"],
    tabelas: ["atend_conversas"],
    erros: ["falha ao persistir estado da sessão"],
  },
  {
    id: "context.load",
    nome: "Contexto da clínica e histórico",
    categoria: "CONTEXTO",
    descricao:
      "Reúne dados da clínica, histórico recente da conversa e mensagens ainda não respondidas.",
    arquivo: "src/lib/nina-contexto.server.ts",
    funcao: "contextoClinicaTexto",
    entrada: "Clínica e conversa",
    saida: "Texto de contexto",
    anteriores: ["session.resolve"],
    seguintes: ["instructions.catalog", "instructions.learnings", "prompt.compose"],
    tabelas: ["clinicas", "unidades", "whatsapp_mensagens"],
    erros: ["clínica sem dados cadastrados"],
  },
  {
    id: "instructions.catalog",
    nome: "Regras do catálogo no prompt",
    categoria: "INSTRUCOES",
    descricao: "Monta o bloco de regras e o resumo do catálogo publicado usado nas instruções.",
    arquivo: "src/lib/nina/catalogo-prompt.server.ts",
    funcao: "blocoPromptCatalogo",
    entrada: "Clínica",
    saida: "Bloco de instruções do catálogo",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
    tabelas: ["nina_cat_servicos", "nina_cat_profissionais"],
    erros: ["catálogo sem publicação"],
  },
  {
    id: "instructions.learnings",
    nome: "Aprendizados aprovados",
    categoria: "INSTRUCOES",
    descricao: "Adiciona ao prompt os aprendizados revisados e aprovados pela equipe.",
    arquivo: "src/lib/nina/aprendizado.server.ts",
    entrada: "Clínica",
    saida: "Bloco de aprendizados",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
    tabelas: ["nina_aprendizados"],
    erros: ["nenhum aprendizado aprovado"],
  },
  {
    id: "prompt.compose",
    nome: "Montagem do prompt",
    categoria: "INSTRUCOES",
    descricao:
      "Compõe as instruções finais: identidade, fase do atendimento, contexto, catálogo e aprendizados.",
    arquivo: "src/lib/nina-contexto.server.ts",
    funcao: "systemPromptNina",
    entrada: "Contexto e blocos de instrução",
    saida: "Prompt do sistema",
    anteriores: ["context.load", "instructions.catalog", "instructions.learnings"],
    seguintes: ["llm.model_flag", "llm.generate"],
    erros: ["prompt acima do limite do modelo"],
  },

  // ───────────────────────── IA ─────────────────────────
  {
    id: "llm.generate",
    nome: "Chamada ao modelo",
    categoria: "IA",
    descricao:
      "Envia prompt, histórico e ferramentas ao gateway de IA e recebe texto ou pedido de ferramenta.",
    arquivo: "src/lib/nina/ai-gateway.server.ts",
    funcao: "ninaAIGateway",
    servico: "Lovable AI Gateway",
    entrada: "Mensagens e ferramentas disponíveis",
    saida: "Resposta de texto ou chamadas de ferramenta",
    anteriores: ["prompt.compose", "llm.model_flag", "tool.execute"],
    seguintes: ["tool.execute", "response.validate", "error.handle"],
    erros: ["limite de uso", "créditos insuficientes", "tempo esgotado", "resposta inválida"],
  },
  {
    id: "llm.model_flag",
    nome: "Seleção de modelo",
    categoria: "IA",
    descricao: "Escolhe o modelo conforme perfil de uso e sinalizador por clínica.",
    arquivo: "src/lib/nina/modelo-flag.server.ts",
    entrada: "Clínica e perfil de uso",
    saida: "Identificador do modelo",
    anteriores: ["prompt.compose"],
    seguintes: ["llm.generate"],
    tabelas: ["clinica_feature_flags"],
    erros: ["sinalizador ausente (usa o modelo padrão)"],
  },

  // ───────────────────────── TOOLS ─────────────────────────
  {
    id: "tool.execute",
    nome: "Execução de ferramentas",
    categoria: "TOOLS",
    descricao:
      "Ponto único que executa as ferramentas pedidas pelo modelo, evita repetição no mesmo turno e limita as rodadas.",
    arquivo: "src/lib/nina/tool-broker.server.ts",
    funcao: "criarToolBroker",
    entrada: "Pedido de ferramenta do modelo",
    saida: "Resultado devolvido ao modelo",
    anteriores: ["llm.generate"],
    seguintes: [
      "tool.catalog.lookup",
      "tool.knowledge.lookup",
      "tool.schedule.availability",
      "tool.schedule.book",
      "tool.patient.lookup",
      "tool.business_hours",
      "tool.handoff",
      "llm.generate",
    ],
    erros: ["ferramenta desconhecida", "limite de rodadas atingido", "chamada repetida no turno"],
  },
  {
    id: "tool.catalog.lookup",
    nome: "Consulta ao catálogo",
    categoria: "CONHECIMENTO",
    descricao:
      "Busca estruturada em serviços e profissionais publicados; é a base de conhecimento oficial usada em produção.",
    arquivo: "src/lib/nina/catalogo-retrieval.server.ts",
    funcao: "buscarNoCatalogo",
    entrada: "Termo e filtros",
    saida: "Registros do catálogo",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["nina_cat_servicos", "nina_cat_profissionais", "nina_kb_consultas"],
    erros: ["nenhum registro publicado", "termo sem correspondência"],
  },
  {
    id: "tool.knowledge.lookup",
    nome: "Base de conhecimento",
    categoria: "CONHECIMENTO",
    descricao:
      "Consulta os registros da base de conhecimento por texto; a busca por similaridade existe no banco mas não é usada por este caminho.",
    arquivo: "src/lib/nina/knowledge.server.ts",
    funcao: "searchKnowledgeBase",
    entrada: "Pergunta do paciente",
    saida: "Trechos encontrados",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["nina_kb_bases", "nina_kb_registros", "nina_kb_consultas"],
    erros: ["base vazia", "sem resultado"],
  },
  {
    id: "tool.business_hours",
    nome: "Horário oficial de funcionamento",
    categoria: "CONHECIMENTO",
    descricao: "Responde a partir do calendário oficial publicado, com exceções e fuso da clínica.",
    arquivo: "src/lib/nina/horario-oficial.ts",
    funcao: "horarioOficialDoDia",
    entrada: "Clínica, unidade e data",
    saida: "Faixas do dia e situação de aberto/fechado",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: [
      "nina_calendario_versoes",
      "nina_calendario_atendimento",
      "nina_calendario_excecoes",
    ],
    erros: ["nenhuma versão publicada", "dia não configurado"],
  },
  {
    id: "tool.schedule.availability",
    nome: "Disponibilidade de agenda",
    categoria: "TOOLS",
    descricao: "Consulta vagas reais liberadas na agenda para especialidade, profissional ou data.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "consultarDisponibilidadeCore",
    entrada: "Filtros de busca",
    saida: "Lista de horários livres",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["agendamentos", "medicos", "procedimentos"],
    erros: ["sem vagas no período", "profissional inexistente"],
  },
  {
    id: "tool.schedule.book",
    nome: "Agendamento pela Nina",
    categoria: "TOOLS",
    descricao:
      "Executa a marcação reutilizando as mesmas regras da tela de Agenda, sem lógica paralela.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    entrada: "Vaga escolhida e paciente identificado",
    saida: "Agendamento criado e confirmação",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["agendamentos", "pacientes"],
    erros: ["vaga já ocupada", "paciente não identificado", "regra da agenda impede a marcação"],
  },
  {
    id: "tool.patient.lookup",
    nome: "Identificação do paciente",
    categoria: "TOOLS",
    descricao: "Localiza o cadastro pelo telefone ou pela combinação de dados informados.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "identificarPaciente",
    entrada: "Telefone ou dados pessoais",
    saida: "Paciente vinculado à conversa",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["pacientes", "atend_conversas"],
    erros: ["nenhum cadastro encontrado", "mais de um cadastro compatível"],
  },
  {
    id: "tool.handoff",
    nome: "Pedido de atendente humano",
    categoria: "TOOLS",
    descricao: "Ferramenta que o modelo aciona para transferir a conversa para uma pessoa.",
    arquivo: "src/lib/nina/handoff-tool.server.ts",
    funcao: "executarHandoffTool",
    entrada: "Motivo da transferência",
    saida: "Transferência solicitada",
    anteriores: ["tool.execute"],
    seguintes: ["handoff.queue"],
    erros: ["conversa já atendida por humano"],
  },

  // ───────────────────────── HANDOFF ─────────────────────────
  {
    id: "handoff.queue",
    nome: "Transferência e fila",
    categoria: "PROCESSAMENTO",
    descricao:
      "Muda o dono da conversa, desliga a resposta automática, registra evento e coloca na fila.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "encaminharParaHumano",
    entrada: "Conversa e motivo",
    saida: "Conversa aguardando atendimento humano",
    anteriores: ["tool.handoff", "routing.decide", "wait.timeout"],
    seguintes: ["handoff.assign", "handoff.summary"],
    tabelas: ["atend_conversas", "atend_conversa_eventos"],
    erros: ["nenhum atendente disponível"],
  },
  {
    id: "handoff.summary",
    nome: "Resumo da transferência",
    categoria: "PROCESSAMENTO",
    descricao: "Gera o resumo do que já foi conversado para quem vai assumir o atendimento.",
    arquivo: "src/lib/atendimento/handoff-resumo.server.ts",
    entrada: "Histórico da conversa",
    saida: "Resumo salvo",
    anteriores: ["handoff.queue"],
    seguintes: [],
    tabelas: ["atend_handoff_resumos"],
    erros: ["falha na geração do resumo (transferência continua)"],
  },
  {
    id: "handoff.assign",
    nome: "Atribuição do atendente",
    categoria: "PROCESSAMENTO",
    descricao: "Distribui a conversa a um atendente disponível com trava no banco.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "atribuirAtendenteOnline",
    entrada: "Conversa na fila",
    saida: "Conversa atribuída",
    anteriores: ["handoff.queue"],
    seguintes: ["protocol.generate"],
    tabelas: ["atend_conversas", "atend_agente_presenca", "atend_transferencias"],
    erros: ["disputa entre atendentes", "ninguém online"],
  },
  {
    id: "protocol.generate",
    nome: "Protocolo do atendimento",
    categoria: "PROCESSAMENTO",
    descricao: "Gera o número de protocolo quando um humano assume a conversa.",
    arquivo: "src/lib/atendimento/protocolo-atendimento.server.ts",
    funcao: "protocoloAoAtribuirHumano",
    entrada: "Conversa atribuída",
    saida: "Protocolo registrado",
    anteriores: ["handoff.assign"],
    seguintes: [],
    tabelas: ["atend_conversas", "atend_protocolo_atendimento_config"],
    erros: ["configuração de protocolo ausente para a clínica"],
  },

  // ───────────────────────── SAÍDA ─────────────────────────
  {
    id: "response.validate",
    nome: "Validação da resposta",
    categoria: "VALIDACAO",
    descricao:
      "Ajusta e valida o texto final antes do envio (limites, formato e regras de conteúdo).",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    entrada: "Texto do modelo",
    saida: "Texto aprovado para envio",
    anteriores: ["llm.generate"],
    seguintes: ["message.outbound"],
    erros: ["resposta vazia", "conteúdo bloqueado"],
  },
  {
    id: "message.outbound",
    nome: "Envio para o WhatsApp",
    categoria: "SAIDA",
    descricao: "Entrega a resposta pela API da Meta, em texto ou áudio.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "metaSendText",
    servico: "Meta WhatsApp Cloud API",
    entrada: "Texto aprovado",
    saida: "Mensagem enviada e identificador da Meta",
    anteriores: ["response.validate"],
    seguintes: ["message.persist", "audio.fallback"],
    erros: ["número inválido", "janela de 24h fechada", "falha da API (sem nova tentativa)"],
  },
  {
    id: "audio.fallback",
    nome: "Áudio com retorno para texto",
    categoria: "ERRO_FALLBACK",
    descricao: "Quando o envio em áudio falha, a mesma resposta segue como texto.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "metaSendAudio",
    servico: "Meta WhatsApp Cloud API",
    entrada: "Áudio gerado",
    saida: "Áudio enviado ou texto equivalente",
    anteriores: ["message.outbound"],
    seguintes: ["message.persist"],
    erros: ["falha ao subir a mídia", "áudio recusado pela Meta"],
  },
  {
    id: "message.persist",
    nome: "Persistência da resposta",
    categoria: "SAIDA",
    descricao: "Grava a mensagem de saída com autoria da Nina e o identificador da execução.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    entrada: "Mensagem enviada",
    saida: "Registro na conversa",
    anteriores: ["message.outbound", "audio.fallback"],
    seguintes: ["wait.start", "conversation.close", "metrics.record"],
    tabelas: ["whatsapp_mensagens"],
    erros: ["falha de gravação após envio"],
  },

  // ───────────────────────── ESPERA E ENCERRAMENTO ─────────────────────────
  {
    id: "wait.start",
    nome: "Espera pela resposta do paciente",
    categoria: "PROCESSAMENTO",
    descricao: "Marca o início da espera quando a Nina fica aguardando o paciente.",
    arquivo: "src/lib/nina/espera-paciente.server.ts",
    entrada: "Resposta enviada",
    saida: "Espera registrada",
    anteriores: ["message.persist"],
    seguintes: ["wait.timeout"],
    tabelas: ["atend_conversas"],
    erros: ["estado de espera inconsistente"],
  },
  {
    id: "wait.timeout",
    nome: "Tempo de espera esgotado",
    categoria: "PROCESSAMENTO",
    descricao: "Processa em lote as conversas paradas além do tempo configurado.",
    arquivo: "src/lib/nina/espera-timeout.server.ts",
    funcao: "processarTimeoutsEsperaPaciente",
    entrada: "Conversas em espera",
    saida: "Encerramento ou transferência",
    anteriores: ["wait.start"],
    seguintes: ["conversation.close", "handoff.queue"],
    tabelas: ["atend_conversas", "atend_conversa_eventos"],
    erros: ["conversa alterada por outro processo durante o lote"],
  },
  {
    id: "conversation.close",
    nome: "Encerramento automático",
    categoria: "PROCESSAMENTO",
    descricao: "Avalia e resolve a conversa pela Nina somente depois do envio confirmado.",
    arquivo: "src/lib/nina/encerramento-automatico.server.ts",
    funcao: "avaliarEncerramentoAutomatico",
    entrada: "Conversa e última resposta",
    saida: "Conversa resolvida ou mantida aberta",
    anteriores: ["message.persist", "wait.timeout"],
    seguintes: ["metrics.record"],
    tabelas: ["atend_conversas", "clinica_feature_flags"],
    erros: ["recurso desativado para a clínica", "conversa já assumida por humano"],
  },

  // ───────────────────────── OBSERVABILIDADE E ERRO ─────────────────────────
  {
    id: "metrics.record",
    nome: "Registro da execução",
    categoria: "OBSERVABILIDADE",
    descricao: "Grava modelo, tokens, tempo, tentativas e ferramentas usadas em cada execução.",
    arquivo: "src/lib/nina/telemetria.server.ts",
    funcao: "registrarExecucao",
    entrada: "Dados da execução",
    saida: "Execução registrada",
    anteriores: ["message.persist", "conversation.close"],
    seguintes: ["evidence.record"],
    tabelas: ["nina_execucoes"],
    erros: ["falha de telemetria (silenciosa)"],
  },
  {
    id: "evidence.record",
    nome: "Evidências por etapa",
    categoria: "OBSERVABILIDADE",
    descricao:
      "Guarda cada etapa da resposta (contexto, consultas, ferramentas, validações) para auditoria posterior.",
    arquivo: "src/lib/nina/evidencias.server.ts",
    funcao: "gravarEvidencias",
    entrada: "Etapas coletadas durante a execução",
    saida: "Evidências gravadas",
    anteriores: ["metrics.record"],
    seguintes: ["metrics.period"],
    tabelas: ["nina_execucao_evidencias"],
    erros: ["gravação melhor-esforço, sem alerta em caso de falha"],
  },
  {
    id: "metrics.period",
    nome: "Métricas por período",
    categoria: "OBSERVABILIDADE",
    descricao:
      "Consolida desempenho dentro e fora do horário oficial para as telas de acompanhamento.",
    arquivo: "src/lib/nina/desempenho-periodo.ts",
    entrada: "Clínica, intervalo e unidade",
    saida: "Indicadores do período",
    anteriores: ["evidence.record"],
    seguintes: [],
    tabelas: ["whatsapp_mensagens", "nina_execucoes", "nina_feedback_erros"],
    erros: ["sem dados no período", "clínica sem calendário publicado"],
  },
  {
    id: "error.handle",
    nome: "Tratamento de erro do fluxo",
    categoria: "ERRO_FALLBACK",
    descricao:
      "Captura falhas do processamento, registra o resultado no log do webhook e responde 200 para evitar reenvio em massa da Meta.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "marcarResultado",
    entrada: "Exceção do processamento",
    saida: "Log de erro e resposta HTTP 200",
    anteriores: ["llm.generate"],
    seguintes: [],
    tabelas: ["whatsapp_webhook_logs", "whatsapp_configs"],
    erros: ["erro não classificado", "ausência de nova tentativa automática"],
  },
];

export const MANIFESTO_ARQUITETURA = {
  versao: 1,
  descricao:
    "Descrição estruturada da arquitetura real da Nina. Não executa nada e não substitui o código.",
  categorias: CATEGORIAS_ARQUITETURA,
  nodes: NODES_ARQUITETURA,
} as const;

export function nodePorId(id: string): NodeArquitetura | undefined {
  return NODES_ARQUITETURA.find((n) => n.id === id);
}

export function nodesPorCategoria(categoria: CategoriaArquitetura): NodeArquitetura[] {
  return NODES_ARQUITETURA.filter((n) => n.categoria === categoria);
}
