/**
 * FASE 1 — MANIFESTO DA ARQUITETURA DA NINA (somente descrição).
 *
 * Este arquivo NÃO executa nada do fluxo da Nina e NÃO duplica regra de
 * negócio. Ele apenas descreve, de forma estruturada, componentes que já
 * existem no backend (arquivo + função reais), para que uma interface futura
 * possa desenhar e auditar a arquitetura.
 *
 * Regras de manutenção:
 *  - todo node deve apontar para arquivo/função que existem no repositório;
 *  - toda conexão deve representar um caminho realmente possível no código;
 *  - nada aqui pode ser importado pelo fluxo de execução da Nina.
 */

export const CATEGORIAS_ARQUITETURA = [
  "ENTRADA",
  "PROCESSAMENTO",
  "CONTEXTO",
  "MEMORIA",
  "INSTRUCOES",
  "CONHECIMENTO",
  "IA",
  "TOOLS",
  "VALIDACAO",
  "SAIDA",
  "OBSERVABILIDADE",
  "ERRO_FALLBACK",
  "HOMOLOGACAO",
] as const;

export type CategoriaArquitetura = (typeof CATEGORIAS_ARQUITETURA)[number];

export type NodeArquitetura = {
  id: string;
  nome: string;
  categoria: CategoriaArquitetura;
  descricao: string;
  /** Caminho relativo à raiz do projeto. */
  arquivo?: string;
  /** Nome de função/const exportada ou interna existente no arquivo. */
  funcao?: string;
  /** Serviço externo ou interno acionado, quando houver. */
  servico?: string;
  entrada: string;
  saida: string;
  anteriores: string[];
  seguintes: string[];
  /** Tabelas do banco lidas ou gravadas por este componente. */
  tabelas?: string[];
  /** Erros reais que este ponto pode produzir ou tratar. */
  erros: string[];
  /**
   * FASE 5 — quem controla o texto que sai daqui:
   *  - "modelo": comportamento configurado nas Instruções da Nina;
   *  - "mensagem_automatica": template versionado, editável e publicável;
   *  - "regra_tecnica": regra protegida, não editável pela configuração.
   */
  controle?: "modelo" | "mensagem_automatica" | "regra_tecnica";
  /** Onde se edita a configuração que controla esta resposta. */
  configuracao?: string;
  /**
   * Nomes reais das ferramentas oferecidas ao modelo que este componente
   * representa. A conferência do mapa compara esta lista com o código.
   */
  ferramentas?: string[];
};

export const NODES_ARQUITETURA: NodeArquitetura[] = [
  // ───────────────────────── ENTRADA ─────────────────────────
  {
    id: "message.inbound",
    nome: "Webhook WhatsApp (entrada)",
    categoria: "ENTRADA",
    descricao:
      "Rota pública que recebe GET de verificação e POST de eventos da WhatsApp Cloud API por clínica.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "Route",
    servico: "Meta WhatsApp Cloud API",
    entrada: "Requisição HTTP da Meta",
    saida: "Payload do evento",
    anteriores: [],
    seguintes: ["message.log_raw"],
    tabelas: ["whatsapp_configs"],
    erros: ["clínica inexistente", "configuração ausente", "payload sem mensagem"],
  },
  {
    id: "message.log_raw",
    nome: "Log bruto do webhook",
    categoria: "OBSERVABILIDADE",
    descricao: "Registra cabeçalhos, corpo e resultado do evento antes de qualquer processamento.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "registrarLogWebhook",
    entrada: "Requisição bruta",
    saida: "Identificador do log",
    anteriores: ["message.inbound"],
    seguintes: ["message.validate"],
    tabelas: ["whatsapp_webhook_logs"],
    erros: ["falha ao gravar log (ignorada, não interrompe o fluxo)"],
  },
  {
    id: "message.validate",
    nome: "Validação de assinatura",
    categoria: "VALIDACAO",
    descricao:
      "Confere a assinatura HMAC-SHA256 do corpo com o app secret. Assinatura ausente ou inválida fica registrada no log do webhook como assinatura_invalida, mas a mensagem do paciente nunca é descartada.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "verifySignature",
    entrada: "Corpo bruto + cabeçalho de assinatura",
    saida: "Resultado da conferência registrado no log",
    anteriores: ["message.log_raw"],
    seguintes: ["message.deduplicate", "status.update", "audio.transcribe"],
    erros: [
      "assinatura inválida (registrada; a mensagem segue)",
      "app secret ausente (registrado; a mensagem segue)",
    ],
  },
  {
    id: "audio.transcribe",
    nome: "Transcrição do áudio recebido",
    categoria: "PROCESSAMENTO",
    descricao:
      "Quando o paciente manda áudio, baixa a mídia da Meta e transcreve para texto antes de gravar a mensagem. É a transcrição que a Nina lê.",
    arquivo: "src/lib/whatsapp-midia.server.ts",
    funcao: "transcreverAudioWhatsapp",
    servico: "Lovable AI Gateway (google/gemini-2.5-flash)",
    entrada: "Áudio recebido pelo WhatsApp",
    saida: "Texto transcrito",
    anteriores: ["message.validate"],
    seguintes: ["message.deduplicate"],
    erros: [
      "falha ao baixar a mídia",
      "transcrição com falha (o paciente recebe a mensagem automática de áudio não compreendido)",
    ],
  },
  {
    id: "status.update",
    nome: "Atualização de status de envio",
    categoria: "OBSERVABILIDADE",
    descricao: "Trata eventos de status (enviado, entregue, lido, falha) das mensagens de saída.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "registrarStatusWhatsapp",
    entrada: "Evento de status da Meta",
    saida: "Mensagem de saída atualizada",
    anteriores: ["message.validate"],
    seguintes: [],
    tabelas: ["whatsapp_mensagens"],
    erros: ["mensagem não encontrada pelo identificador da Meta"],
  },
  {
    id: "message.deduplicate",
    nome: "Deduplicação e persistência da entrada",
    categoria: "PROCESSAMENTO",
    descricao:
      "Grava a mensagem recebida; o identificador único da Meta impede processar o mesmo evento duas vezes. Um reenvio da Meta reaproveita a entrada já gravada.",
    arquivo: "src/lib/nina/entrada-persistida.server.ts",
    funcao: "persistirEntradaNina",
    entrada: "Evento validado (com a transcrição, quando for áudio)",
    saida: "Mensagem persistida ou descarte por duplicidade",
    anteriores: ["message.validate", "audio.transcribe"],
    seguintes: ["reminder.reply"],
    tabelas: ["whatsapp_mensagens"],
    erros: ["duplicidade (descartada)", "falha de gravação"],
  },
  {
    id: "reminder.reply",
    nome: "Resposta ao lembrete de consulta",
    categoria: "PROCESSAMENTO",
    descricao:
      "Antes da Nina, reconhece a resposta do paciente ao lembrete automático de consulta. Quando reconhecida, atualiza a agenda respeitando mudanças da recepção, envia uma linha de fechamento e não aciona a Nina nem a fila.",
    arquivo: "src/lib/agenda/confirmacao-whatsapp.server.ts",
    funcao: "processarRespostaConfirmacao",
    entrada: "Mensagem gravada do paciente",
    saida: "Agenda atualizada e fechamento enviado, ou mensagem segue para a próxima checagem",
    anteriores: ["message.deduplicate"],
    seguintes: ["verification.code"],
    tabelas: ["agendamento_confirmacoes", "agendamentos", "whatsapp_mensagens"],
    erros: [
      "resposta não reconhecida (segue para o atendimento)",
      "falha no reconhecimento (a mensagem segue; nunca é engolida)",
    ],
  },
  {
    id: "verification.code",
    nome: "Código de verificação do site",
    categoria: "PROCESSAMENTO",
    descricao:
      "Reconhece a mensagem que é só o código de confirmação pedido pelo site (API v1.2). Quando reconhecida, responde uma linha curta, sem dados do cadastro, e encerra sem abrir conversa nem acionar a Nina.",
    arquivo: "src/lib/integracoes/verificacao-v1.server.ts",
    funcao: "reconhecerCodigoVerificacao",
    entrada: "Texto da mensagem e número do remetente",
    saida: "Código confirmado e resposta curta, ou mensagem segue para o atendimento",
    anteriores: ["reminder.reply"],
    seguintes: ["conversation.reopen", "routing.decide"],
    tabelas: ["integracao_verificacoes", "whatsapp_mensagens"],
    erros: [
      "código não reconhecido (segue para o atendimento)",
      "falha ao responder ao paciente (registrada)",
    ],
  },
  {
    id: "conversation.ensure",
    nome: "Conversa e identidade do contato",
    categoria: "PROCESSAMENTO",
    descricao:
      "Já dentro do turno, recupera a conversa do número e o que se sabe da identidade do paciente (confirmação, cadastro ligado e estado salvo do atendimento). Não há busca de paciente por telefone em nenhum ambiente: o número do WhatsApp fica guardado para o cadastro.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "carregarEstadoIdentidade",
    entrada: "Telefone e clínica",
    saida: "Estado da conversa e da identidade",
    anteriores: ["turn.batch"],
    seguintes: ["session.resolve"],
    tabelas: ["atend_conversas", "pacientes"],
    erros: ["conversa não localizada", "falha ao ler a identidade (segue sem paciente identificado)"],
  },
  {
    id: "conversation.reopen",
    nome: "Reabertura por mensagem do paciente",
    categoria: "PROCESSAMENTO",
    descricao: "Conversa encerrada volta a ficar ativa quando o paciente escreve de novo.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "reabrirConversaPorMensagemPaciente",
    entrada: "Conversa encerrada + nova mensagem",
    saida: "Conversa reaberta e evento registrado",
    anteriores: ["verification.code"],
    seguintes: ["routing.decide"],
    tabelas: ["atend_conversas", "atend_conversa_eventos"],
    erros: ["falha ao atualizar estado da conversa"],
  },
  {
    id: "routing.decide",
    nome: "Decisão Nina ou humano",
    categoria: "PROCESSAMENTO",
    descricao:
      "Decide se a Nina pode responder. Ela não responde quando a conversa já está com um atendente ou na fila humana, nem quando foi desligada na clínica. Nesses casos, se a conversa ainda não tem responsável, vai na hora para um atendente online.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "ninaPodeResponder",
    entrada: "Estado da conversa",
    saida: "Autorização ou bloqueio da resposta automática",
    anteriores: ["verification.code", "conversation.reopen"],
    seguintes: ["turn.batch", "handoff.assign"],
    tabelas: ["atend_conversas", "clinica_feature_flags"],
    erros: ["estado inconsistente da conversa", "ninguém online (a conversa fica em Não atribuídas)"],
  },
  {
    id: "turn.batch",
    nome: "Agrupamento e trava do turno",
    categoria: "PROCESSAMENTO",
    descricao:
      "Junta mensagens seguidas do mesmo paciente num único turno (espera 1 segundo sem mensagem nova, no máximo 2,5 segundos) e reserva a conversa enquanto a Nina responde, para não sair resposta dupla. Se chegar mensagem mais nova, ela assume o turno e a anterior encerra sem responder.",
    arquivo: "src/lib/nina/burst.server.ts",
    funcao: "aguardarTurnoNina",
    entrada: "Mensagem liberada para a Nina",
    saida: "Turno com as mensagens do paciente e a conversa reservada",
    anteriores: ["routing.decide"],
    seguintes: ["conversation.ensure"],
    tabelas: ["nina_message_batches", "nina_conversa_locks"],
    erros: [
      "turno assumido por mensagem mais nova (encerra sem responder)",
      "falha ao agrupar antes de começar (a rota pede à Meta para reenviar)",
    ],
  },

  // ───────────────────────── CONTEXTO E MEMÓRIA ─────────────────────────
  {
    id: "session.resolve",
    nome: "Sessão da conversa",
    categoria: "MEMORIA",
    descricao: "Resolve a sessão vigente por tempo de inatividade e persiste o estado atualizado.",
    arquivo: "src/lib/nina/sessao.server.ts",
    funcao: "resolverSessao",
    entrada: "Conversa e horário da mensagem",
    saida: "Sessão vigente ou nova",
    anteriores: ["conversation.ensure"],
    seguintes: ["context.load", "flow.state", "instructions.greeting"],
    tabelas: ["atend_conversas"],
    erros: ["falha ao persistir estado da sessão"],
  },
  {
    id: "context.load",
    nome: "Contexto enviado ao modelo",
    categoria: "CONTEXTO",
    descricao:
      "Monta o que vai para o modelo: instruções, janela recente da conversa na mesma sessão e campos mínimos do paciente. Histórico completo, cadastro e agenda inteiros nunca são enviados.",
    arquivo: "src/lib/nina/context-builder.ts",
    funcao: "montarContexto",
    entrada: "Instruções, histórico da sessão e estado do atendimento",
    saida: "Mensagens para o modelo",
    anteriores: ["session.resolve", "flow.state", "test.inbound"],
    seguintes: [
      "instructions.published",
      "instructions.catalog",
      "instructions.learnings",
      "instructions.phases",
      "identity.gate",
      "prompt.compose",
      "response.templates",
      "jev.filtro",
    ],

    tabelas: ["whatsapp_mensagens"],
    erros: ["histórico acima do limite (vai só a janela recente)"],
  },
  {
    id: "instructions.catalog",
    nome: "Catálogo publicado no turno",
    categoria: "INSTRUCOES",
    descricao:
      "Lê o catálogo publicado uma única vez por resposta e informa se há serviços e profissionais publicados. No WhatsApp, as regras de leitura do catálogo vêm das Instruções publicadas e os detalhes entram pelas ferramentas de consulta.",
    arquivo: "src/lib/nina/catalogo-prompt.server.ts",
    funcao: "contarCatalogoPublicado",
    entrada: "Clínica",
    saida: "Quantidade de serviços e profissionais publicados",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
    tabelas: ["nina_cat_servicos", "nina_cat_profissionais"],
    erros: ["catálogo sem publicação"],
  },
  {
    id: "instructions.learnings",
    nome: "Aprendizados aprovados",
    categoria: "INSTRUCOES",
    descricao: "Adiciona ao prompt os aprendizados revisados e aprovados pela equipe.",
    arquivo: "src/lib/nina/aprendizado.server.ts",
    entrada: "Clínica",
    saida: "Bloco de aprendizados",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
    tabelas: ["nina_aprendizados"],
    erros: ["nenhum aprendizado aprovado"],
  },
  {
    id: "instructions.published",
    nome: "Instruções da Nina (versão publicada)",
    categoria: "INSTRUCOES",
    descricao:
      "Carrega no backend a versão publicada das Instruções da Nina, com cache curto, snapshot por execução e retorno à última versão válida em caso de falha. O conteúdo editável define só o comportamento da conversa — nunca permissões, acesso a dados ou confirmações obrigatórias.",
    arquivo: "src/lib/nina/instrucoes-runtime.server.ts",
    funcao: "promptInstrucoes",
    entrada: "Escopo do atendimento e valores dinâmicos da conversa",
    saida: "Texto base do Prompt Principal e a versão utilizada",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
    tabelas: ["nina_instrucoes_versoes"],
    erros: [
      "nenhuma versão publicada (usa o texto do código)",
      "marcador dinâmico não resolvido",
      "falha de leitura (usa a última versão válida)",
    ],
  },
  {
    id: "prompt.compose",
    nome: "Montagem do prompt",
    categoria: "INSTRUCOES",
    descricao:
      "Compõe as instruções finais a partir da versão publicada das Instruções da Nina, somando identidade, fase do atendimento, contexto, catálogo e aprendizados.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    entrada: "Instruções publicadas e blocos de contexto",
    saida: "Prompt do sistema",
    anteriores: [
      "context.load",
      "instructions.published",
      "instructions.catalog",
      "instructions.learnings",
      "instructions.greeting",
      "instructions.phases",
      "identity.gate",
      "jev.filtro",
    ],
    seguintes: ["llm.model_flag", "llm.generate"],
    erros: ["prompt acima do limite do modelo"],
  },

  // ───────────────────────── IA ─────────────────────────
  {
    id: "llm.generate",
    nome: "Chamada ao modelo",
    categoria: "IA",
    descricao:
      "Envia prompt, histórico e ferramentas ao gateway de IA e recebe texto ou pedido de ferramenta. Pode repetir várias rodadas no mesmo turno: pede ferramentas, recebe o resultado e continua.",
    arquivo: "src/lib/nina/ai-gateway.server.ts",
    funcao: "ninaAIGateway",
    servico: "Lovable AI Gateway (google/gemini-3.8-flash)",
    entrada: "Mensagens e ferramentas disponíveis",
    saida: "Resposta de texto ou chamadas de ferramenta",
    anteriores: [
      "prompt.compose",
      "llm.model_flag",
      "tool.execute",
      "tool.catalog.lookup",
      "tool.catalog.list",
      "tool.knowledge.lookup",
      "tool.business_hours",
      "tool.schedule.availability",
      "tool.doctor_schedule",
      "tool.schedule.select",
      "tool.schedule.book",
      "tool.my_appointments",
      "patient.link",
      "response.guard",
      "voice.reasoning",
    ],
    seguintes: [
      "tool.execute",
      "response.finalize",
      "response.guard",
      "error.handle",
      "metrics.record",
    ],
    erros: ["limite de uso", "créditos insuficientes", "tempo esgotado", "resposta inválida"],
  },
  {
    id: "llm.model_flag",
    nome: "Modelo da Nina (fixo)",
    categoria: "IA",
    descricao:
      "Modelo único google/gemini-3.8-flash para todas as clínicas e perfis desde 25/09/2026. A antiga escolha por clínica foi retirada e as linhas antigas da flag ficaram sem efeito.",
    arquivo: "src/lib/nina/modelo-flag.server.ts",
    funcao: "modeloNinaParaClinica",
    entrada: "Clínica e perfil de uso (não mudam o modelo)",
    saida: "google/gemini-3.8-flash",
    anteriores: ["prompt.compose"],
    seguintes: ["llm.generate"],
    erros: ["modelo indisponível no provedor (vira falha da chamada ao modelo)"],
  },
  {
    id: "jev.filtro",
    nome: "Filtro de decisão (Jev)",
    categoria: "IA",
    descricao:
      "Igual em produção e homologação, ligado por fase na clínica. Fase 1 confirma a intenção da mensagem, com o histórico em ordem e as opções já oferecidas. Fase 2 encaminha para a equipe em urgência, pedido de atendente, irritação ou três falhas seguidas de entendimento sem avanço do atendimento, igual à CONV-04: até duas perguntas de esclarecimento antes de encaminhar (escolher uma opção oferecida não conta). Fase 3 escolhe a especialidade quando a busca não acha; fase 4 deixa sugestão de cadastro para a recepção. Erro ou demora mantém o fluxo normal.",
    arquivo: "src/lib/nina/jev.server.ts",
    funcao: "perguntarJev",
    servico: "Lovable AI Gateway (typesafe/jev-latest)",
    entrada: "Mensagem, histórico do ciclo e contexto do atendimento",
    saida: "Intenção, encaminhamento, especialidade ou sugestão de cadastro",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose", "handoff.queue"],
    tabelas: ["nina_jev_decisoes", "clinica_feature_flags"],
    erros: ["flag da fase desligada (não roda)", "erro ou demora (segue o fluxo normal)"],
  },

  // ───────────────────────── TOOLS ─────────────────────────
  {
    id: "tool.execute",
    nome: "Execução de ferramentas",
    categoria: "TOOLS",
    descricao:
      "Ponto único que executa as ferramentas pedidas pelo modelo e evita repetir a mesma chamada no turno. Ferramentas que gravam ou mostram dados do paciente só rodam com o agendamento pela Nina ativo na clínica (ligado por padrão). O limite de rodadas fica no núcleo do atendimento.",
    arquivo: "src/lib/nina/tool-broker.server.ts",
    funcao: "criarToolBroker",
    entrada: "Pedido de ferramenta do modelo",
    saida: "Resultado devolvido ao modelo",
    anteriores: ["llm.generate"],
    seguintes: [
      "tool.catalog.lookup",
      "tool.catalog.list",
      "tool.knowledge.lookup",
      "tool.schedule.availability",
      "tool.doctor_schedule",
      "tool.schedule.select",
      "tool.schedule.book",
      "tool.my_appointments",
      "tool.patient.lookup",
      "tool.business_hours",
      "tool.handoff",
      "llm.generate",
    ],
    erros: ["ferramenta desconhecida", "limite de rodadas atingido", "chamada repetida no turno"],
  },
  {
    id: "tool.catalog.lookup",
    nome: "Consulta ao catálogo",
    categoria: "CONHECIMENTO",
    descricao:
      "Busca estruturada em serviços e profissionais publicados; é a base de conhecimento oficial usada em produção.",
    arquivo: "src/lib/nina/catalogo-retrieval.server.ts",
    funcao: "buscarNoCatalogo",
    entrada: "Termo e filtros",
    saida: "Registros do catálogo",
    anteriores: ["tool.execute", "tool.knowledge.lookup"],
    seguintes: ["llm.generate"],
    tabelas: ["nina_cat_servicos", "nina_cat_profissionais", "nina_kb_consultas"],
    erros: ["nenhum registro publicado", "termo sem correspondência"],
  },
  {
    id: "tool.knowledge.lookup",
    nome: "Pergunta à base de conhecimento",
    categoria: "CONHECIMENTO",
    descricao:
      "Porta de entrada da ferramenta consultar_base_conhecimento: repassa a pergunta para a busca no catálogo publicado e registra a consulta. A antiga base de registros de texto não é consultada por este caminho.",
    arquivo: "src/lib/nina/knowledge.server.ts",
    funcao: "searchKnowledgeBase",
    entrada: "Pergunta do paciente",
    saida: "Registros do catálogo publicado",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate", "tool.catalog.lookup"],
    tabelas: ["nina_kb_consultas"],
    erros: ["pergunta sem correspondência no catálogo", "catálogo sem publicação"],
    ferramentas: ["consultar_base_conhecimento"],
  },
  {
    id: "tool.business_hours",
    nome: "Horário oficial de funcionamento",
    categoria: "CONHECIMENTO",
    descricao: "Responde a partir do calendário oficial publicado, com exceções e fuso da clínica.",
    arquivo: "src/lib/nina/horario-oficial.ts",
    funcao: "horarioOficialDoDia",
    entrada: "Clínica, unidade e data",
    saida: "Faixas do dia e situação de aberto/fechado",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["nina_calendario_versoes", "nina_calendario_atendimento", "nina_calendario_excecoes"],
    erros: ["nenhuma versão publicada", "dia não configurado"],
    ferramentas: ["horario_funcionamento"],
  },
  {
    id: "tool.schedule.availability",
    nome: "Disponibilidade de agenda",
    categoria: "TOOLS",
    descricao: "Consulta vagas reais liberadas na agenda para especialidade, profissional ou data.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "consultarDisponibilidadeCore",
    entrada: "Filtros de busca",
    saida: "Lista de horários livres",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["agendamentos", "medicos", "procedimentos"],
    erros: ["sem vagas no período", "profissional inexistente"],
    ferramentas: ["consultar_disponibilidade"],
  },
  {
    id: "tool.schedule.select",
    nome: "Escolha do horário",
    categoria: "TOOLS",
    descricao:
      "Ferramenta selecionar_horario: interpreta a escolha do paciente entre as vagas devolvidas pela agenda e revalida a vaga. Não cria reserva: a marcação só acontece depois do resumo final aceito pelo paciente em mensagem seguinte, pela ferramenta agendar.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    entrada: "Horário escolhido pelo paciente",
    saida: "Vaga revalidada para o resumo de confirmação",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["agendamentos"],
    erros: ["vaga não está mais livre", "escolha ambígua (a Nina pergunta antes)"],
    ferramentas: ["selecionar_horario"],
  },
  {
    id: "tool.schedule.book",
    nome: "Agendamento pela Nina",
    categoria: "TOOLS",
    descricao:
      "Ferramenta agendar: grava só a vaga do resumo final aceito pelo paciente, reutilizando as mesmas regras da tela de Agenda, sem lógica paralela.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    entrada: "Vaga escolhida e paciente identificado",
    saida: "Agendamento criado e confirmação",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["agendamentos", "pacientes"],
    erros: ["vaga já ocupada", "paciente não identificado", "regra da agenda impede a marcação"],
    ferramentas: ["agendar"],
  },
  {
    id: "tool.patient.lookup",
    nome: "Identificação e cadastro do paciente",
    categoria: "TOOLS",
    descricao:
      "Ferramentas identificar_paciente e consultar_cadastro_paciente: localizam ou criam o cadastro pelo número do WhatsApp da conversa (na homologação, o número virtual do lead), o nome completo e a data de nascimento — CPF não é usado. Ligam o paciente à conversa e apontam os campos obrigatórios que faltam antes da confirmação.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    entrada: "Dados pessoais informados pelo paciente",
    saida: "Paciente vinculado à conversa ou campos que faltam",
    anteriores: ["tool.execute"],
    seguintes: ["patient.link"],
    tabelas: ["pacientes", "atend_conversas"],
    erros: ["nenhum cadastro encontrado", "mais de um cadastro compatível"],
    ferramentas: ["identificar_paciente", "consultar_cadastro_paciente"],
  },
  {
    id: "tool.handoff",
    nome: "Pedido de atendente humano",
    categoria: "TOOLS",
    descricao:
      "Ferramenta solicitar_atendente_humano: o modelo aciona quando o paciente pede uma pessoa ou uma regra manda encaminhar. O servidor também a aciona sozinho quando uma regra do catálogo exige encaminhamento.",
    arquivo: "src/lib/nina/handoff-tool.server.ts",
    funcao: "executarHandoffTool",
    entrada: "Motivo da transferência",
    saida: "Transferência solicitada",
    anteriores: ["tool.execute"],
    seguintes: ["handoff.queue"],
    erros: ["conversa já atendida por humano"],
    ferramentas: ["solicitar_atendente_humano"],
  },

  // ───────────────────────── HANDOFF ─────────────────────────
  {
    id: "handoff.queue",
    nome: "Transferência e fila",
    categoria: "PROCESSAMENTO",
    descricao:
      "Muda o dono da conversa, desliga a resposta automática, registra evento, coloca na fila e avisa o paciente com o protocolo — a única mensagem de transferência do turno. Na homologação é simulado: nenhuma atendente real é acionada e o aviso leva a nota de simulação.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "encaminharParaHumano",
    entrada: "Conversa e motivo",
    saida: "Conversa aguardando atendimento humano",
    anteriores: ["tool.handoff", "wait.timeout", "turn.watchdog", "jev.filtro"],
    seguintes: ["handoff.assign", "handoff.summary"],
    tabelas: ["atend_conversas", "atend_conversa_eventos"],
    erros: ["nenhum atendente disponível"],
  },
  {
    id: "handoff.summary",
    nome: "Resumo da transferência",
    categoria: "PROCESSAMENTO",
    descricao: "Gera o resumo do que já foi conversado para quem vai assumir o atendimento.",
    arquivo: "src/lib/atendimento/handoff-resumo.server.ts",
    entrada: "Histórico da conversa",
    saida: "Resumo salvo",
    anteriores: ["handoff.queue"],
    seguintes: [],
    tabelas: ["atend_handoff_resumos"],
    erros: ["falha na geração do resumo (transferência continua)"],
  },
  {
    id: "handoff.assign",
    nome: "Atribuição do atendente",
    categoria: "PROCESSAMENTO",
    descricao:
      "Distribui a conversa ao atendente online com menos conversas, com trava no banco. Também recebe na hora as conversas que já são da equipe e ainda não têm responsável.",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "atribuirAtendenteOnline",
    entrada: "Conversa na fila",
    saida: "Conversa atribuída",
    anteriores: ["handoff.queue", "routing.decide"],
    seguintes: ["protocol.generate"],
    tabelas: ["atend_conversas", "atend_agente_presenca", "atend_transferencias"],
    erros: ["disputa entre atendentes", "ninguém online"],
  },
  {
    id: "protocol.generate",
    nome: "Protocolo do atendimento",
    categoria: "PROCESSAMENTO",
    descricao: "Gera o número de protocolo quando um humano assume a conversa.",
    arquivo: "src/lib/atendimento/protocolo-atendimento.server.ts",
    funcao: "protocoloAoAtribuirHumano",
    entrada: "Conversa atribuída",
    saida: "Protocolo registrado",
    anteriores: ["handoff.assign"],
    seguintes: [],
    tabelas: ["atend_conversas", "atend_protocolo_atendimento_config"],
    erros: ["configuração de protocolo ausente para a clínica"],
  },

  // ───────────────────────── SAÍDA ─────────────────────────
  {
    id: "response.templates",
    nome: "Templates das mensagens automáticas",
    categoria: "INSTRUCOES",
    descricao:
      "Textos versionados das mensagens que NÃO passam pelo modelo: coleta de dados, erro, confirmação de agendamento, transferência, mídia e despedida. Sem versão publicada, vale o texto padrão do sistema.",
    arquivo: "src/lib/nina/resposta/templates.server.ts",
    funcao: "carregarTemplatesPublicados",
    entrada: "Clínica e escopo do turno",
    saida: "Mapa de chave para texto publicado",
    anteriores: ["context.load"],
    seguintes: ["response.finalize"],
    tabelas: ["nina_mensagens_templates"],
    erros: ["template inválido", "variável não permitida", "sem publicação (usa o padrão)"],
    controle: "mensagem_automatica",
    configuracao: "Nina › Arquitetura › Mensagens automáticas",
  },
  {
    id: "response.finalize",
    nome: "Finalização da resposta",
    categoria: "SAIDA",
    descricao:
      "Ponto único onde toda resposta (modelo, gate, transferência, mídia, erro e encerramento) recebe o texto final para entrega direta, sem motor de confiança. O transporte não acrescenta nada depois.",
    arquivo: "src/lib/nina/resposta/finalizacao.server.ts",
    funcao: "finalizarResposta",
    entrada: "Resultado estruturado do turno",
    saida: "Texto final aprovado e decisão de encerramento",
    anteriores: ["llm.generate", "response.templates", "response.guard"],
    seguintes: ["response.validate"],
    erros: ["texto vazio", "ação sem evidência real de gravação"],
    controle: "regra_tecnica",
    configuracao: "Regra técnica protegida (não editável)",
  },
  {
    id: "response.validate",
    nome: "Registro do texto final",
    categoria: "SAIDA",
    descricao:
      "Registra o texto final, sua origem e eventuais transformações antes de devolvê-lo ao transporte. Não calcula confiança nem revisa as informações do modelo.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    entrada: "Texto do modelo",
    saida: "Texto preparado para envio",
    anteriores: ["response.finalize"],
    seguintes: ["turn.stale"],
    erros: ["resposta vazia"],
    controle: "regra_tecnica",
    configuracao: "Regra técnica protegida (não editável)",
  },
  {
    id: "turn.stale",
    nome: "Descarte de resposta obsoleta",
    categoria: "VALIDACAO",
    descricao:
      "Antes de qualquer envio, e antes de ações que gravam, confere se o paciente escreveu de novo enquanto a Nina trabalhava. Se escreveu, a resposta antiga é descartada e o turno mais novo responde com o contexto completo.",
    arquivo: "src/lib/nina/revisao-conversa.server.ts",
    funcao: "respostaObsoleta",
    entrada: "Resposta pronta e revisão da conversa usada no turno",
    saida: "Resposta liberada para envio ou descartada",
    anteriores: ["response.validate"],
    seguintes: ["message.outbound"],
    tabelas: ["nina_conversa_revisoes"],
    erros: ["resposta obsoleta (descartada e registrada, sem envio)"],
  },
  {
    id: "message.outbound",
    nome: "Envio para o WhatsApp",
    categoria: "SAIDA",
    descricao:
      "Entrega a resposta pela API da Meta, em texto ou áudio, e registra cada parte entregue para o vigia do turno conferir.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "metaSendText",
    servico: "Meta WhatsApp Cloud API",
    entrada: "Texto aprovado",
    saida: "Mensagem enviada e identificador da Meta",
    anteriores: ["turn.stale"],
    seguintes: ["message.persist", "audio.fallback"],
    erros: [
      "número inválido",
      "janela de 24h fechada",
      "falha recuperável da Meta (o vigia tenta entregar de novo)",
      "retorno incerto da Meta (o vigia encaminha para a equipe com a frase padrão)",
      "entrega recusada pela Meta (registrada como falha)",
    ],
  },
  {
    id: "audio.fallback",
    nome: "Resposta em áudio (com retorno para texto)",
    categoria: "ERRO_FALLBACK",
    descricao:
      "Quando o paciente mandou áudio e a resposta em áudio está ativa na clínica, a resposta vira fala: curta vai inteira; longa ou em lista vira um resumo falado e o texto completo segue por escrito. Se a conversão ou o envio do áudio falhar, a resposta vai em texto.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "metaSendAudio",
    servico: "Meta WhatsApp Cloud API",
    entrada: "Áudio gerado",
    saida: "Áudio enviado ou texto equivalente",
    anteriores: ["message.outbound"],
    seguintes: ["message.persist"],
    erros: ["falha ao subir a mídia", "áudio recusado pela Meta"],
  },
  {
    id: "message.persist",
    nome: "Persistência da resposta",
    categoria: "SAIDA",
    descricao: "Grava a mensagem de saída com autoria da Nina e o identificador da execução.",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    entrada: "Mensagem enviada",
    saida: "Registro na conversa",
    anteriores: ["message.outbound", "audio.fallback"],
    seguintes: ["wait.start", "conversation.close", "metrics.record"],
    tabelas: ["whatsapp_mensagens"],
    erros: ["falha de gravação após envio"],
  },

  // ───────────────────────── ESPERA E ENCERRAMENTO ─────────────────────────
  {
    id: "wait.start",
    nome: "Espera pela resposta do paciente",
    categoria: "PROCESSAMENTO",
    descricao:
      "Após cada mensagem enviada pela Nina, inicia 30 minutos sem retorno do paciente enquanto a conversa estiver exclusivamente com ela, exceto se houver agendamento comprovado na sessão atual.",
    arquivo: "src/lib/nina/espera-paciente.server.ts",
    entrada: "Resposta enviada",
    saida: "Espera registrada",
    anteriores: ["message.persist"],
    seguintes: ["wait.timeout_job"],
    tabelas: ["atend_conversas"],
    erros: ["estado de espera inconsistente"],
  },
  {
    id: "wait.timeout",
    nome: "Tempo de espera esgotado",
    categoria: "PROCESSAMENTO",
    descricao:
      "O job periódico encaminha para a equipe após 30 minutos sem retorno à última mensagem da Nina. Agendamento comprovado na sessão dispensa a transferência e cancela o prazo. Revalida mensagem, sessão, estado e responsável antes de transferir.",
    arquivo: "src/lib/nina/espera-timeout.server.ts",
    funcao: "processarTimeoutsEsperaPaciente",
    entrada: "Conversas em espera",
    saida: "Transferência para atendimento humano",
    anteriores: ["wait.timeout_job"],
    seguintes: ["handoff.queue"],
    tabelas: ["atend_conversas", "atend_conversa_eventos"],
    erros: ["conversa alterada por outro processo durante o lote"],
  },
  {
    id: "conversation.close",
    nome: "Encerramento automático",
    categoria: "PROCESSAMENTO",
    descricao: "Avalia e resolve a conversa pela Nina somente depois do envio confirmado.",
    arquivo: "src/lib/nina/encerramento-automatico.server.ts",
    funcao: "avaliarEncerramentoAutomatico",
    entrada: "Conversa e última resposta",
    saida: "Conversa resolvida ou mantida aberta",
    anteriores: ["message.persist"],
    seguintes: ["metrics.record"],
    tabelas: ["atend_conversas", "clinica_feature_flags"],
    erros: ["recurso desativado para a clínica", "conversa já assumida por humano"],
  },

  // ───────────────────────── OBSERVABILIDADE E ERRO ─────────────────────────
  {
    id: "metrics.record",
    nome: "Registro da execução",
    categoria: "OBSERVABILIDADE",
    descricao: "Grava modelo, tokens, tempo, tentativas e ferramentas usadas em cada execução.",
    arquivo: "src/lib/nina/telemetria.server.ts",
    funcao: "registrarExecucao",
    entrada: "Dados da execução",
    saida: "Execução registrada",
    anteriores: ["llm.generate", "message.persist", "conversation.close"],
    seguintes: ["evidence.record"],
    tabelas: ["nina_execucoes"],
    erros: ["falha de telemetria (silenciosa)"],
  },
  {
    id: "evidence.record",
    nome: "Evidências por etapa",
    categoria: "OBSERVABILIDADE",
    descricao:
      "Guarda cada etapa da resposta (contexto, consultas, ferramentas, validações) para auditoria posterior.",
    arquivo: "src/lib/nina/evidencias.server.ts",
    funcao: "gravarEvidencias",
    entrada: "Etapas coletadas durante a execução",
    saida: "Evidências gravadas",
    anteriores: ["metrics.record"],
    seguintes: ["metrics.period", "trace.record"],
    tabelas: ["nina_execucao_evidencias"],
    erros: ["gravação melhor-esforço, sem alerta em caso de falha"],
  },
  {
    id: "metrics.period",
    nome: "Métricas por período",
    categoria: "OBSERVABILIDADE",
    descricao:
      "Consolida desempenho dentro e fora do horário oficial para as telas de acompanhamento.",
    arquivo: "src/lib/nina/desempenho-periodo.ts",
    entrada: "Clínica, intervalo e unidade",
    saida: "Indicadores do período",
    anteriores: ["evidence.record"],
    seguintes: [],
    tabelas: ["whatsapp_mensagens", "nina_execucoes", "nina_feedback_erros"],
    erros: ["sem dados no período", "clínica sem calendário publicado"],
  },
  {
    id: "error.handle",
    nome: "Tratamento de erro do fluxo",
    categoria: "ERRO_FALLBACK",
    descricao:
      "Registra a falha no log do webhook e aciona o vigia do turno, que decide entre retomar, reenviar ou encaminhar para a equipe com a frase padrão. Se a falha acontece antes de a Nina começar (ao agrupar as mensagens), a rota responde 503 para a Meta reenviar com segurança; nos demais casos responde 200.",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "marcarResultado",
    entrada: "Exceção do processamento",
    saida: "Log de erro, resposta HTTP e acionamento do vigia",
    anteriores: ["llm.generate"],
    seguintes: ["turn.watchdog"],
    tabelas: ["whatsapp_webhook_logs", "whatsapp_configs"],
    erros: ["erro não classificado (registrado no log)", "reenvio pela Meta só quando nada foi processado"],
  },
  {
    id: "turn.watchdog",
    nome: "Vigia do turno",
    categoria: "ERRO_FALLBACK",
    descricao:
      "Acompanha cada turno por etapas. Turno travado é retomado de onde parou, sem repetir modelo, ferramentas ou encaminhamento, em até 3 tentativas; entrega com falha recuperável é reenviada. Sem sucesso, ou quando a entrega fica incerta, avisa o paciente com a frase padrão de encaminhamento e coloca a conversa na fila humana.",
    arquivo: "src/lib/nina/watchdog.server.ts",
    funcao: "executarWatchdogNina",
    entrada: "Turnos com falha ou parados",
    saida: "Turno retomado, entrega refeita ou conversa encaminhada para a equipe",
    anteriores: ["error.handle", "wait.timeout_job"],
    seguintes: ["handoff.queue"],
    tabelas: ["nina_message_batches", "nina_batch_entregas"],
    erros: [
      "limite de tentativas atingido (encaminha para a equipe)",
      "conversa já com a equipe ou Nina desligada (encerra sem responder)",
    ],
  },
  {
    id: "response.guard",
    nome: "Correção de agendamento não confirmado",
    categoria: "VALIDACAO",
    descricao:
      "Se o modelo afirma ou promete um agendamento sem gravação confirmada no turno, o sistema pede uma correção ao modelo uma vez; se a afirmação continuar, troca o texto por um aviso de que o agendamento não foi concluído.",
    arquivo: "src/lib/nina/afirmacao-agendamento.ts",
    funcao: "afirmaOuPrometeAgendamento",
    entrada: "Texto do modelo e situação do agendamento no turno",
    saida: "Nova rodada de correção ou texto substituído",
    anteriores: ["llm.generate"],
    seguintes: ["llm.generate", "response.finalize"],
    erros: ["afirmação de agendamento sem gravação (corrigida antes do envio)"],
  },
  {
    id: "data.retention",
    nome: "Limpeza automática de registros",
    categoria: "OBSERVABILIDADE",
    descricao:
      "Função do banco nina_zap_retencao_executar, agendada de hora em hora pelo agendador do banco quando a migration de retenção está aplicada. Apaga execuções, evidências, rastros, lotes, travas e dados de teste com mais de 7 dias, e conversas, mensagens e confirmações com mais de 3 meses.",
    servico: "Agendador do banco (pg_cron)",
    entrada: "Registros gravados pelo atendimento e horário agendado",
    saida: "Registros antigos apagados e resumo da limpeza",
    anteriores: ["trace.record"],
    seguintes: [],
    tabelas: [
      "nina_execucoes",
      "nina_execucao_evidencias",
      "nina_trace_eventos",
      "whatsapp_mensagens",
      "atend_conversas",
    ],
    erros: [
      "agendador indisponível no banco (a limpeza não roda)",
      "falha em uma tabela (registrada; as demais seguem)",
    ],
  },

  // ───────── FASE 1 DA SINCRONIZAÇÃO: componentes reais que faltavam ─────────
  {
    id: "flow.state",
    nome: "Estado do fluxo do atendimento",
    categoria: "MEMORIA",
    descricao:
      "Recupera da própria conversa a etapa do atendimento e os dados já informados, e salva as mudanças a cada turno. É o que mantém o paciente identificado de uma mensagem para a outra.",
    arquivo: "src/lib/nina/fluxo-estado.server.ts",
    funcao: "salvarFluxoEstado",
    entrada: "Conversa e sessão vigente",
    saida: "Estado do fluxo e bloco de prompt correspondente",
    anteriores: ["session.resolve"],
    seguintes: ["context.load"],
    tabelas: ["atend_conversas"],
    erros: ["estado corrompido (recomeça do zero)", "falha ao salvar o estado"],
  },
  {
    id: "instructions.greeting",
    nome: "Validação da apresentação da sessão",
    categoria: "INSTRUCOES",
    descricao:
      "Observa se a apresentação exigida pela sessão apareceu uma única vez na resposta. Não altera o texto: a apresentação vem do prompt publicado em Arquitetura.",
    arquivo: "src/lib/nina/saudacao-sessao.ts",
    funcao: "avaliarSaudacao",
    entrada: "Sessão e texto da resposta",
    saida: "Diagnóstico (ausente/duplicada) para telemetria",
    anteriores: ["session.resolve"],
    seguintes: ["prompt.compose"],
    erros: ["saudação repetida na mesma sessão", "sessão sem marcação de saudação"],
  },
  {
    id: "instructions.phases",
    nome: "Intenção e etapa do atendimento",
    categoria: "INSTRUCOES",
    descricao:
      "Detecta a intenção da mensagem e, com as flags das fases ligadas, deriva a etapa do atendimento e os dados que ainda faltam. Isso vai ao modelo como fato do contexto de execução, não como texto de instrução: o comportamento de cada etapa vem das Instruções publicadas.",
    arquivo: "src/lib/nina/atendimento-fase1.ts",
    funcao: "detectarIntencoes",
    entrada: "Mensagem do paciente e estado do fluxo",
    saida: "Intenções, etapa atual e dados faltantes",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
    erros: ["intenção ambígua", "fase sem dados suficientes"],
  },
  {
    id: "identity.gate",
    nome: "Trava de identificação do paciente",
    categoria: "VALIDACAO",
    descricao:
      "Impede avançar para confirmação de agendamento antes de identificar o paciente, tratando negações e assuntos paralelos.",
    arquivo: "src/lib/nina/identificacao-gate.server.ts",
    funcao: "aplicarGateIdentificacao",
    entrada: "Mensagem e estado da identificação",
    saida: "Liberação ou pedido de dados de identificação",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
    tabelas: ["pacientes", "atend_conversas"],
    erros: ["dados incompletos", "paciente recusa se identificar"],
  },
  {
    id: "patient.link",
    nome: "Vínculo paciente ↔ conversa",
    categoria: "PROCESSAMENTO",
    descricao: "Liga o cadastro encontrado à conversa do número, para o restante do atendimento.",
    arquivo: "src/lib/atendimento/vinculo-contato.server.ts",
    funcao: "vincularPacienteConversa",
    entrada: "Paciente identificado e conversa",
    saida: "Conversa vinculada ao cadastro",
    anteriores: ["tool.patient.lookup"],
    seguintes: ["llm.generate"],
    tabelas: ["atend_conversas", "pacientes"],
    erros: ["conversa já vinculada a outro cadastro", "falha ao gravar o vínculo"],
  },
  {
    id: "tool.catalog.list",
    nome: "Especialidades, médicos, procedimentos e dados da clínica",
    categoria: "TOOLS",
    descricao:
      "Ferramentas de listagem usadas pelo modelo: listar_especialidades, buscar_medicos, buscar_procedimentos e dados_da_clinica.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "listarEspecialidades",
    entrada: "Filtro informado pelo modelo",
    saida: "Listas do catálogo publicado",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["nina_cat_servicos", "nina_cat_profissionais", "clinicas", "unidades"],
    erros: ["catálogo sem publicação", "filtro sem correspondência"],
    ferramentas: ["listar_especialidades", "buscar_medicos", "buscar_procedimentos", "dados_da_clinica"],
  },
  {
    id: "tool.doctor_schedule",
    nome: "Escala do profissional e próxima vaga",
    categoria: "TOOLS",
    descricao:
      "Ferramentas verificar_horario, proxima_vaga e consultar_primeiro_disponivel: dizem em que dias o profissional atende, qual a próxima vaga real e a primeira vaga livre.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "escalaDoMedico",
    entrada: "Profissional, especialidade ou data",
    saida: "Dias de atendimento e próxima vaga",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["agendamentos", "medicos"],
    erros: ["profissional sem escala", "nenhuma vaga futura"],
    ferramentas: ["verificar_horario", "proxima_vaga", "consultar_primeiro_disponivel"],
  },
  {
    id: "tool.my_appointments",
    nome: "Agendamentos do paciente",
    categoria: "TOOLS",
    descricao: "Ferramenta meus_agendamentos: lista as marcações do paciente já identificado.",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    entrada: "Paciente identificado",
    saida: "Agendamentos futuros e recentes",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
    tabelas: ["agendamentos"],
    erros: ["paciente não identificado", "nenhum agendamento encontrado"],
    ferramentas: ["meus_agendamentos"],
  },
  {
    id: "voice.inbound",
    nome: "Canal de voz da Nina",
    categoria: "ENTRADA",
    descricao:
      "Endpoints internos de fala e voz usados pelo atendimento por áudio, fora do webhook do WhatsApp.",
    arquivo: "src/routes/api/nina-fala.ts",
    funcao: "Route",
    entrada: "Áudio ou texto do canal de voz",
    saida: "Pedido de resposta para o modelo",
    anteriores: [],
    seguintes: ["voice.reasoning"],
    erros: ["áudio inválido", "sessão de voz ausente"],
  },
  {
    id: "voice.reasoning",
    nome: "Nível de raciocínio do canal de voz",
    categoria: "IA",
    descricao:
      "Escolhe o nível de raciocínio do modelo no canal de voz, com escalonamento que não regride durante a conversa.",
    arquivo: "src/lib/nina/reasoning-router.ts",
    funcao: "selectThinkingLevel",
    entrada: "Mensagem e nível anterior",
    saida: "Nível de raciocínio aplicado",
    anteriores: ["voice.inbound"],
    seguintes: ["llm.generate"],
    erros: ["nível inválido (usa o padrão)"],
  },
  {
    id: "wait.timeout_job",
    nome: "Rotina do vigia (a cada minuto)",
    categoria: "PROCESSAMENTO",
    descricao:
      "O agendador chama a rota autenticada do vigia a cada minuto, mesmo sem mensagens novas ou navegador aberto. A cada chamada: encaminha conversas sem retorno há 30 minutos, recupera turnos travados e dá sequência a testes de carga pendentes.",
    arquivo: "src/routes/api/public/nina.watchdog.ts",
    funcao: "executarJobWatchdog",
    entrada: "Chamada do agendador",
    saida: "Esperas vencidas, turnos travados e cargas pendentes processados",
    anteriores: ["wait.start"],
    seguintes: ["wait.timeout", "turn.watchdog"],
    erros: ["chamada não autorizada", "nada pendente"],
  },
  {
    id: "trace.record",
    nome: "Rastro técnico da execução",
    categoria: "OBSERVABILIDADE",
    descricao:
      "Grava os eventos por etapa (início, fim, falha, nova tentativa) usados pela aba Arquitetura, sem bloquear o atendimento.",
    arquivo: "src/lib/nina/arquitetura/tracing.server.ts",
    funcao: "gravarEventosTrace",
    entrada: "Eventos coletados durante a execução",
    saida: "Rastro consultável por mensagem",
    anteriores: ["evidence.record"],
    seguintes: ["test.evaluate.sol", "data.retention"],
    tabelas: ["nina_trace_eventos"],
    erros: ["gravação melhor-esforço, sem alerta em caso de falha"],
  },
  // ─────────────────────── HOMOLOGAÇÃO (ambiente de teste) ───────────────────────
  {
    id: "test.cycle",
    nome: "Ciclo do lead de teste",
    categoria: "HOMOLOGACAO",
    descricao:
      "Garante a conversa e o ciclo de cada um dos 10 leads de teste; resolver o teste encerra o ciclo e a próxima mensagem abre outro, sem memória do anterior.",
    arquivo: "src/lib/nina/teste-console.server.ts",
    funcao: "garantirCiclo",
    entrada: "Lead de teste da clínica",
    saida: "Conversa e ciclo de teste ativos",
    anteriores: [],
    seguintes: ["test.inbound"],
    tabelas: ["nina_teste_leads", "nina_teste_ciclos", "atend_conversas"],
    erros: ["lead de teste inexistente", "ciclo já encerrado (resposta atrasada descartada)"],
  },
  {
    id: "test.inbound",
    nome: "Entrada da homologação",
    categoria: "HOMOLOGACAO",
    descricao:
      "Recebe a mensagem escrita pelo operador ou gerada por simulador, grava como mensagem de teste e chama o mesmo núcleo da Nina, com as mesmas decisões da produção. Não envia pelo WhatsApp e o encaminhamento é simulado: nenhuma atendente real é acionada e a mensagem de transferência leva o aviso de simulação. A agenda consultada é a real.",
    arquivo: "src/lib/nina/teste-console.server.ts",
    funcao: "processarMensagemTeste",
    entrada: "Mensagem do paciente de teste",
    saida: "Execução da Nina em modo homologação",
    anteriores: ["test.cycle", "test.patient.terra", "test.scenario.run", "test.load.luna"],
    seguintes: ["context.load"],
    tabelas: ["whatsapp_mensagens", "atend_conversas", "nina_teste_ciclos"],
    erros: ["mensagem vazia", "mensagem duplicada", "lead sem ciclo ativo"],
  },
  {
    id: "test.patient.terra",
    nome: "Paciente simulado (GPT Terra)",
    categoria: "HOMOLOGACAO",
    descricao:
      "Gera a próxima fala do paciente simulado a partir do cenário, da persona e do histórico visível; não executa ferramentas e não recebe o prompt principal.",
    arquivo: "src/lib/nina/simulador-terra.functions.ts",
    funcao: "proximaMensagemTerra",
    servico: "Lovable AI Gateway (openai/gpt-5.6-terra)",
    entrada: "Cenário, persona e histórico da conversa de teste",
    saida: "Mensagem do paciente simulado",
    anteriores: [],
    seguintes: ["test.inbound"],
    tabelas: ["nina_teste_simulacoes"],
    erros: ["limite de turnos atingido", "simulação pausada ou parada", "falha do modelo"],
  },
  {
    id: "test.scenario.run",
    nome: "Execução de cenários",
    categoria: "HOMOLOGACAO",
    descricao:
      "Distribui os cenários da biblioteca entre os leads de teste, executa cada item e registra critérios atendidos.",
    arquivo: "src/lib/nina/cenarios.functions.ts",
    funcao: "iniciarItemExecucao",
    entrada: "Cenários selecionados e leads disponíveis",
    saida: "Itens de execução com resultado por critério",
    anteriores: ["test.regression"],
    seguintes: ["test.inbound"],
    tabelas: ["nina_teste_cenarios", "nina_teste_execucoes", "nina_teste_execucao_itens"],
    erros: ["nenhum lead livre", "execução parada pelo operador"],
  },
  {
    id: "test.load.luna",
    nome: "Teste de carga (GPT Luna)",
    categoria: "HOMOLOGACAO",
    descricao:
      "Controlador determinístico de volume: define ritmo, concorrência e tentativas; o Luna gera variações de texto sintético e, na bateria por profissional, escreve o paciente conforme a resposta da Nina. Cada cenário da bateria termina com verificação e devolução da vaga de teste.",
    arquivo: "src/lib/nina/carga.functions.ts",
    funcao: "executarLoteCarga",
    servico: "Lovable AI Gateway (openai/gpt-5.6-luna)",
    entrada: "Perfil de carga, leads e quantidade de mensagens",
    saida: "Lote de mensagens sintéticas enviadas ao ambiente de teste",
    anteriores: [],
    seguintes: ["test.inbound"],
    tabelas: ["nina_teste_carga", "nina_teste_carga_amostras", "agendamentos"],
    erros: ["limite do perfil excedido", "teste cancelado", "falha ao gerar variação"],
  },
  {
    id: "test.evaluate.sol",
    nome: "Avaliação posterior (Jev + Claude Opus 5.5)",
    categoria: "HOMOLOGACAO",
    descricao:
      "Avaliador independente executado DEPOIS da conversa de teste: analisa mensagens, traces, ferramentas e resultados reais e devolve score, veredito e achados com evidência. Com a fase 5 do Jev ligada na clínica, o Jev avalia primeiro e o Claude Opus só entra quando o Jev pede. Não participa da geração da resposta.",
    arquivo: "src/lib/nina/avaliador-sol.functions.ts",
    funcao: "avaliarComSol",
    servico: "Lovable AI Gateway (Jev e Claude Opus 5.5)",
    entrada: "Conversa de teste já concluída e seus rastros",
    saida: "Avaliação com score, veredito e achados",
    anteriores: ["trace.record"],
    seguintes: ["test.report"],
    tabelas: ["nina_teste_avaliacoes"],
    erros: ["conversa sem mensagens", "achado sem evidência (descartado)", "falha do modelo"],
  },
  {
    id: "test.report",
    nome: "Relatório da homologação",
    categoria: "HOMOLOGACAO",
    descricao:
      "Agrega, por execução de teste, mensagens, ferramentas, RAG, agendamentos, transferências, erros, tokens, versão do prompt e a avaliação do Sol.",
    arquivo: "src/lib/nina/relatorio-teste.functions.ts",
    funcao: "detalheRelatorioTeste",
    entrada: "Execução manual, Terra, cenário ou carga",
    saida: "Relatório consolidado com links para conversa, trace e prompt",
    anteriores: ["test.evaluate.sol"],
    seguintes: ["test.review"],
    tabelas: ["nina_execucoes", "nina_trace_eventos", "nina_teste_avaliacoes"],
    erros: ["execução não encontrada", "sem permissão na clínica"],
  },
  {
    id: "test.review",
    nome: "Envio para Revisão de Aprendizados",
    categoria: "HOMOLOGACAO",
    descricao:
      "Transforma um achado do Sol em item revisável por pessoas, com evidência, trace e versão do prompt. Nada é aplicado automaticamente.",
    arquivo: "src/lib/nina/revisao-teste.functions.ts",
    funcao: "enviarAchadoParaRevisao",
    entrada: "Achado da avaliação com evidência",
    saida: "Item na fila de revisão humana",
    anteriores: ["test.report"],
    seguintes: ["test.regression"],
    tabelas: ["nina_feedback_erros"],
    erros: ["achado sem evidência", "item já enviado (idempotente)"],
  },
  {
    id: "test.regression",
    nome: "Teste de regressão",
    categoria: "HOMOLOGACAO",
    descricao:
      "Após decisão humana sobre o achado, cria um cenário de regressão reexecutável em mudanças futuras.",
    arquivo: "src/lib/nina/revisao-teste.functions.ts",
    funcao: "criarTesteRegressaoDeAchado",
    entrada: "Achado confirmado ou aprovado por uma pessoa",
    saida: "Cenário de regressão na biblioteca de testes",
    anteriores: ["test.review"],
    seguintes: ["test.scenario.run"],
    tabelas: ["nina_feedback_erros", "nina_teste_cenarios"],
    erros: ["achado ainda sem decisão humana", "cenário já criado"],
  },
];

export const MANIFESTO_ARQUITETURA = {
  versao: 6,
  descricao:
    "Descrição estruturada da arquitetura real da Nina. Não executa nada e não substitui o código.",
  /** Modelo que o mapa declara para a Nina; a conferência compara com o código. */
  modelo: "google/gemini-3.8-flash",
  /** Última revisão completa do mapa contra o código (data ISO). */
  revisadoEm: "2026-09-25",
  categorias: CATEGORIAS_ARQUITETURA,
  nodes: NODES_ARQUITETURA,
} as const;

export function nodePorId(id: string): NodeArquitetura | undefined {
  return NODES_ARQUITETURA.find((n) => n.id === id);
}

export function nodesPorCategoria(categoria: CategoriaArquitetura): NodeArquitetura[] {
  return NODES_ARQUITETURA.filter((n) => n.categoria === categoria);
}
