// Snapshot imutável do manifesto v6, antes da inclusão do motivo de encaminhamento.
import type { AssinaturaNode } from "./sync";
export const SNAPSHOT_V6: AssinaturaNode[] = [
  {
    id: "message.inbound",
    categoria: "ENTRADA",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "Route",
    anteriores: [],
    seguintes: ["message.log_raw"],
  },
  {
    id: "message.log_raw",
    categoria: "OBSERVABILIDADE",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "registrarLogWebhook",
    anteriores: ["message.inbound"],
    seguintes: ["message.validate"],
  },
  {
    id: "message.validate",
    categoria: "VALIDACAO",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "verifySignature",
    anteriores: ["message.log_raw"],
    seguintes: ["audio.transcribe", "message.deduplicate", "status.update"],
  },
  {
    id: "audio.transcribe",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/whatsapp-midia.server.ts",
    funcao: "transcreverAudioWhatsapp",
    anteriores: ["message.validate"],
    seguintes: ["message.deduplicate"],
  },
  {
    id: "status.update",
    categoria: "OBSERVABILIDADE",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "registrarStatusWhatsapp",
    anteriores: ["message.validate"],
    seguintes: [],
  },
  {
    id: "message.deduplicate",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/nina/entrada-persistida.server.ts",
    funcao: "persistirEntradaNina",
    anteriores: ["audio.transcribe", "message.validate"],
    seguintes: ["reminder.reply"],
  },
  {
    id: "reminder.reply",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/agenda/confirmacao-whatsapp.server.ts",
    funcao: "processarRespostaConfirmacao",
    anteriores: ["message.deduplicate"],
    seguintes: ["verification.code"],
  },
  {
    id: "verification.code",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/integracoes/verificacao-v1.server.ts",
    funcao: "reconhecerCodigoVerificacao",
    anteriores: ["reminder.reply"],
    seguintes: ["conversation.reopen", "routing.decide"],
  },
  {
    id: "conversation.ensure",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "carregarEstadoIdentidade",
    anteriores: ["turn.batch"],
    seguintes: ["session.resolve"],
  },
  {
    id: "conversation.reopen",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "reabrirConversaPorMensagemPaciente",
    anteriores: ["verification.code"],
    seguintes: ["routing.decide"],
  },
  {
    id: "routing.decide",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "ninaPodeResponder",
    anteriores: ["conversation.reopen", "verification.code"],
    seguintes: ["handoff.assign", "turn.batch"],
  },
  {
    id: "turn.batch",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/nina/burst.server.ts",
    funcao: "aguardarTurnoNina",
    anteriores: ["routing.decide"],
    seguintes: ["conversation.ensure"],
  },
  {
    id: "session.resolve",
    categoria: "MEMORIA",
    arquivo: "src/lib/nina/sessao.server.ts",
    funcao: "resolverSessao",
    anteriores: ["conversation.ensure"],
    seguintes: ["context.load", "flow.state", "instructions.greeting"],
  },
  {
    id: "context.load",
    categoria: "CONTEXTO",
    arquivo: "src/lib/nina/context-builder.ts",
    funcao: "montarContexto",
    anteriores: ["flow.state", "session.resolve", "test.inbound"],
    seguintes: [
      "identity.gate",
      "instructions.catalog",
      "instructions.learnings",
      "instructions.phases",
      "instructions.published",
      "jev.filtro",
      "prompt.compose",
      "response.templates",
    ],
  },
  {
    id: "instructions.catalog",
    categoria: "INSTRUCOES",
    arquivo: "src/lib/nina/catalogo-prompt.server.ts",
    funcao: "contarCatalogoPublicado",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
  },
  {
    id: "instructions.learnings",
    categoria: "INSTRUCOES",
    arquivo: "src/lib/nina/aprendizado.server.ts",
    funcao: null,
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
  },
  {
    id: "instructions.published",
    categoria: "INSTRUCOES",
    arquivo: "src/lib/nina/instrucoes-runtime.server.ts",
    funcao: "promptInstrucoes",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
  },
  {
    id: "prompt.compose",
    categoria: "INSTRUCOES",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    anteriores: [
      "context.load",
      "identity.gate",
      "instructions.catalog",
      "instructions.greeting",
      "instructions.learnings",
      "instructions.phases",
      "instructions.published",
      "jev.filtro",
    ],
    seguintes: ["llm.generate", "llm.model_flag"],
  },
  {
    id: "llm.generate",
    categoria: "IA",
    arquivo: "src/lib/nina/ai-gateway.server.ts",
    funcao: "ninaAIGateway",
    anteriores: [
      "llm.model_flag",
      "patient.link",
      "prompt.compose",
      "response.guard",
      "tool.business_hours",
      "tool.catalog.list",
      "tool.catalog.lookup",
      "tool.doctor_schedule",
      "tool.execute",
      "tool.knowledge.lookup",
      "tool.my_appointments",
      "tool.schedule.availability",
      "tool.schedule.book",
      "tool.schedule.select",
      "voice.reasoning",
    ],
    seguintes: [
      "error.handle",
      "metrics.record",
      "response.finalize",
      "response.guard",
      "tool.execute",
    ],
  },
  {
    id: "llm.model_flag",
    categoria: "IA",
    arquivo: "src/lib/nina/modelo-flag.server.ts",
    funcao: "modeloNinaParaClinica",
    anteriores: ["prompt.compose"],
    seguintes: ["llm.generate"],
  },
  {
    id: "jev.filtro",
    categoria: "IA",
    arquivo: "src/lib/nina/jev.server.ts",
    funcao: "perguntarJev",
    anteriores: ["context.load"],
    seguintes: ["handoff.queue", "prompt.compose"],
  },
  {
    id: "tool.execute",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/tool-broker.server.ts",
    funcao: "criarToolBroker",
    anteriores: ["llm.generate"],
    seguintes: [
      "llm.generate",
      "tool.business_hours",
      "tool.catalog.list",
      "tool.catalog.lookup",
      "tool.doctor_schedule",
      "tool.handoff",
      "tool.knowledge.lookup",
      "tool.my_appointments",
      "tool.patient.lookup",
      "tool.prefetch",
      "tool.schedule.availability",
      "tool.schedule.book",
      "tool.schedule.select",
    ],
  },
  {
    id: "tool.prefetch",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/prefetch-cadastro.server.ts",
    funcao: "executarPrefetchCadastro",
    anteriores: ["tool.execute"],
    seguintes: [],
  },
  {
    id: "tool.catalog.lookup",
    categoria: "CONHECIMENTO",
    arquivo: "src/lib/nina/catalogo-retrieval.server.ts",
    funcao: "buscarNoCatalogo",
    anteriores: ["tool.execute", "tool.knowledge.lookup"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.knowledge.lookup",
    categoria: "CONHECIMENTO",
    arquivo: "src/lib/nina/knowledge.server.ts",
    funcao: "searchKnowledgeBase",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate", "tool.catalog.lookup"],
  },
  {
    id: "tool.business_hours",
    categoria: "CONHECIMENTO",
    arquivo: "src/lib/nina/horario-oficial.ts",
    funcao: "horarioOficialDoDia",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.schedule.availability",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "consultarDisponibilidadeCore",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.schedule.select",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.schedule.book",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.patient.lookup",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    anteriores: ["tool.execute"],
    seguintes: ["patient.link"],
  },
  {
    id: "tool.handoff",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/handoff-tool.server.ts",
    funcao: "executarHandoffTool",
    anteriores: ["tool.execute"],
    seguintes: ["handoff.queue"],
  },
  {
    id: "handoff.queue",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "encaminharParaHumano",
    anteriores: ["jev.filtro", "tool.handoff", "turn.watchdog", "wait.timeout"],
    seguintes: ["handoff.assign", "handoff.summary"],
  },
  {
    id: "handoff.summary",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/atendimento/handoff-resumo.server.ts",
    funcao: null,
    anteriores: ["handoff.queue"],
    seguintes: [],
  },
  {
    id: "handoff.assign",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/atendimento/handoff.server.ts",
    funcao: "atribuirAtendenteOnline",
    anteriores: ["handoff.queue", "routing.decide"],
    seguintes: ["protocol.generate"],
  },
  {
    id: "protocol.generate",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/atendimento/protocolo-atendimento.server.ts",
    funcao: "protocoloAoAtribuirHumano",
    anteriores: ["handoff.assign"],
    seguintes: [],
  },
  {
    id: "response.templates",
    categoria: "INSTRUCOES",
    arquivo: "src/lib/nina/resposta/templates.server.ts",
    funcao: "carregarTemplatesPublicados",
    anteriores: ["context.load"],
    seguintes: ["response.finalize"],
  },
  {
    id: "response.finalize",
    categoria: "SAIDA",
    arquivo: "src/lib/nina/resposta/finalizacao.server.ts",
    funcao: "finalizarResposta",
    anteriores: ["llm.generate", "response.guard", "response.templates"],
    seguintes: ["response.validate"],
  },
  {
    id: "response.validate",
    categoria: "SAIDA",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    anteriores: ["response.finalize"],
    seguintes: ["turn.stale"],
  },
  {
    id: "turn.stale",
    categoria: "VALIDACAO",
    arquivo: "src/lib/nina/revisao-conversa.server.ts",
    funcao: "respostaObsoleta",
    anteriores: ["response.validate"],
    seguintes: ["message.outbound"],
  },
  {
    id: "message.outbound",
    categoria: "SAIDA",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "metaSendText",
    anteriores: ["turn.stale"],
    seguintes: ["audio.fallback", "message.persist"],
  },
  {
    id: "audio.fallback",
    categoria: "ERRO_FALLBACK",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "metaSendAudio",
    anteriores: ["message.outbound"],
    seguintes: ["message.persist"],
  },
  {
    id: "message.persist",
    categoria: "SAIDA",
    arquivo: "src/lib/whatsapp.server.ts",
    funcao: "gerarRespostaNinaInterno",
    anteriores: ["audio.fallback", "message.outbound"],
    seguintes: ["conversation.close", "metrics.record", "wait.start"],
  },
  {
    id: "wait.start",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/nina/espera-paciente.server.ts",
    funcao: null,
    anteriores: ["message.persist"],
    seguintes: ["wait.timeout_job"],
  },
  {
    id: "wait.timeout",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/nina/espera-timeout.server.ts",
    funcao: "processarTimeoutsEsperaPaciente",
    anteriores: ["wait.timeout_job"],
    seguintes: ["handoff.queue"],
  },
  {
    id: "conversation.close",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/nina/encerramento-automatico.server.ts",
    funcao: "avaliarEncerramentoAutomatico",
    anteriores: ["message.persist"],
    seguintes: ["metrics.record"],
  },
  {
    id: "metrics.record",
    categoria: "OBSERVABILIDADE",
    arquivo: "src/lib/nina/telemetria.server.ts",
    funcao: "registrarExecucao",
    anteriores: ["conversation.close", "llm.generate", "message.persist"],
    seguintes: ["evidence.record"],
  },
  {
    id: "evidence.record",
    categoria: "OBSERVABILIDADE",
    arquivo: "src/lib/nina/evidencias.server.ts",
    funcao: "gravarEvidencias",
    anteriores: ["metrics.record"],
    seguintes: ["metrics.period", "trace.record"],
  },
  {
    id: "metrics.period",
    categoria: "OBSERVABILIDADE",
    arquivo: "src/lib/nina/desempenho-periodo.ts",
    funcao: null,
    anteriores: ["evidence.record"],
    seguintes: [],
  },
  {
    id: "error.handle",
    categoria: "ERRO_FALLBACK",
    arquivo: "src/routes/api/public/whatsapp.$clinicaId.ts",
    funcao: "marcarResultado",
    anteriores: ["llm.generate"],
    seguintes: ["turn.watchdog"],
  },
  {
    id: "turn.watchdog",
    categoria: "ERRO_FALLBACK",
    arquivo: "src/lib/nina/watchdog.server.ts",
    funcao: "executarWatchdogNina",
    anteriores: ["error.handle", "wait.timeout_job"],
    seguintes: ["handoff.queue"],
  },
  {
    id: "response.guard",
    categoria: "VALIDACAO",
    arquivo: "src/lib/nina/afirmacao-agendamento.ts",
    funcao: "afirmaOuPrometeAgendamento",
    anteriores: ["llm.generate"],
    seguintes: ["llm.generate", "response.finalize"],
  },
  {
    id: "data.retention",
    categoria: "OBSERVABILIDADE",
    arquivo: null,
    funcao: null,
    anteriores: ["trace.record"],
    seguintes: [],
  },
  {
    id: "flow.state",
    categoria: "MEMORIA",
    arquivo: "src/lib/nina/fluxo-estado.server.ts",
    funcao: "salvarFluxoEstado",
    anteriores: ["session.resolve"],
    seguintes: ["context.load"],
  },
  {
    id: "instructions.greeting",
    categoria: "INSTRUCOES",
    arquivo: "src/lib/nina/saudacao-sessao.ts",
    funcao: "avaliarSaudacao",
    anteriores: ["session.resolve"],
    seguintes: ["prompt.compose"],
  },
  {
    id: "instructions.phases",
    categoria: "INSTRUCOES",
    arquivo: "src/lib/nina/atendimento-fase1.ts",
    funcao: "detectarIntencoes",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
  },
  {
    id: "identity.gate",
    categoria: "VALIDACAO",
    arquivo: "src/lib/nina/identificacao-gate.server.ts",
    funcao: "aplicarGateIdentificacao",
    anteriores: ["context.load"],
    seguintes: ["prompt.compose"],
  },
  {
    id: "patient.link",
    categoria: "PROCESSAMENTO",
    arquivo: "src/lib/atendimento/vinculo-contato.server.ts",
    funcao: "vincularPacienteConversa",
    anteriores: ["tool.patient.lookup"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.catalog.list",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "listarEspecialidades",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.doctor_schedule",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "escalaDoMedico",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
  },
  {
    id: "tool.my_appointments",
    categoria: "TOOLS",
    arquivo: "src/lib/nina/paciente-tools.server.ts",
    funcao: "executarFerramentaPaciente",
    anteriores: ["tool.execute"],
    seguintes: ["llm.generate"],
  },
  {
    id: "voice.inbound",
    categoria: "ENTRADA",
    arquivo: "src/routes/api/nina-fala.ts",
    funcao: "Route",
    anteriores: [],
    seguintes: ["voice.reasoning"],
  },
  {
    id: "voice.reasoning",
    categoria: "IA",
    arquivo: "src/lib/nina/reasoning-router.ts",
    funcao: "selectThinkingLevel",
    anteriores: ["voice.inbound"],
    seguintes: ["llm.generate"],
  },
  {
    id: "wait.timeout_job",
    categoria: "PROCESSAMENTO",
    arquivo: "src/routes/api/public/nina.watchdog.ts",
    funcao: "executarJobWatchdog",
    anteriores: ["wait.start"],
    seguintes: ["turn.watchdog", "wait.timeout"],
  },
  {
    id: "trace.record",
    categoria: "OBSERVABILIDADE",
    arquivo: "src/lib/nina/arquitetura/tracing.server.ts",
    funcao: "gravarEventosTrace",
    anteriores: ["evidence.record"],
    seguintes: ["data.retention", "test.evaluate.sol"],
  },
  {
    id: "test.cycle",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/teste-console.server.ts",
    funcao: "garantirCiclo",
    anteriores: [],
    seguintes: ["test.inbound"],
  },
  {
    id: "test.inbound",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/teste-console.server.ts",
    funcao: "processarMensagemTeste",
    anteriores: ["test.cycle", "test.load.luna", "test.patient.terra", "test.scenario.run"],
    seguintes: ["context.load"],
  },
  {
    id: "test.patient.terra",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/simulador-terra.functions.ts",
    funcao: "proximaMensagemTerra",
    anteriores: [],
    seguintes: ["test.inbound"],
  },
  {
    id: "test.scenario.run",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/cenarios.functions.ts",
    funcao: "iniciarItemExecucao",
    anteriores: ["test.regression"],
    seguintes: ["test.inbound"],
  },
  {
    id: "test.load.luna",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/carga.functions.ts",
    funcao: "executarLoteCarga",
    anteriores: [],
    seguintes: ["test.inbound"],
  },
  {
    id: "test.evaluate.sol",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/avaliador-sol.functions.ts",
    funcao: "avaliarComSol",
    anteriores: ["trace.record"],
    seguintes: ["test.report"],
  },
  {
    id: "test.report",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/relatorio-teste.functions.ts",
    funcao: "detalheRelatorioTeste",
    anteriores: ["test.evaluate.sol"],
    seguintes: ["test.review"],
  },
  {
    id: "test.review",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/revisao-teste.functions.ts",
    funcao: "enviarAchadoParaRevisao",
    anteriores: ["test.report"],
    seguintes: ["test.regression"],
  },
  {
    id: "test.regression",
    categoria: "HOMOLOGACAO",
    arquivo: "src/lib/nina/revisao-teste.functions.ts",
    funcao: "criarTesteRegressaoDeAchado",
    anteriores: ["test.review"],
    seguintes: ["test.scenario.run"],
  },
];
