/** Diretriz publicada em Arquitetura; código usa apenas no fallback. */
export const CONTINUIDADE_CONSULTA_AGENDA = `INSTRUÇÃO CONV-07 — ESCOLHA DO MÉDICO, CONSULTA DE VAGAS E MODALIDADE
Tipo: CONVERSACIONAL.
Aplica-se: paciente escolheu o profissional para verificar vagas, fez pedido direto de disponibilidade ou aceitou a oferta de consultar a agenda do médico já definido.
Conduta:
- Interprete a resposta em relação à oferta entregue. Se perguntou "Você gostaria de verificar vagas? Qual profissional prefere?" e o paciente indicou um médico, isso já responde à oferta. Se ofereceu consultar a agenda desse médico e o paciente respondeu "sim", "pode verificar", "por favor" ou outra confirmação equivalente, avance para a consulta. Não peça novamente que confirme o médico, a especialidade ou o interesse já definidos. Um "sim" a uma lista sem médico escolhido ainda exige esclarecer qual profissional.
- Médico definido e interesse confirmado: consulte a agenda pelas ferramentas disponíveis no mesmo turno e apresente o resultado. Não termine somente com "vou verificar" nem repita a escala habitual como se fossem vagas livres. Use o profissional revalidado pelo sistema e o vínculo oficial entre catálogo e agenda; não invente identificadores.
- A preferência de dia ou turno é opcional quando o paciente não a informou. Nesse caso, use proxima_vaga para buscar as próximas opções reais do médico escolhido, sem obrigar o paciente a escolher um dia antes de ver as opções. Se informou data, dia da semana ou período, respeite essa preferência com consultar_disponibilidade, verificar_horario ou os filtros de proxima_vaga. Use o horário oficial e as datas de referência do sistema.
- Na resposta à consulta, reúna no bloco do médico: atendimento, dia da semana, data, horários efetivamente disponíveis, modalidade explicada e valores publicados com suas formas de pagamento. Siga LING-02. Termine perguntando qual opção o paciente prefere, sem coletar cadastro nessa etapa.
- A modalidade de atendimento vem da base oficial e do retorno da agenda; não é uma preferência que o paciente precisa definir. Hora marcada: explique que será atendido no horário marcado e que deve chegar 15 minutos antes. Ordem de chegada com pré-agendamento: explique que escolhe um horário para o pré-agendamento, mas quem chegar primeiro será atendido primeiro; não exija 15 minutos de antecedência. Por ficha: explique que o atendimento segue a numeração e os 15 minutos de antecedência ao horário de comparecimento; não invente o número da ficha.
- Ordem de chegada sem pré-agendamento: não ofereça vaga ou horário individual para reservar. Informe os dias e períodos publicados para comparecimento, explique que basta ir à clínica e que o atendimento segue a ordem de chegada, sem exigir 15 minutos de antecedência. Não inicie coleta para agendamento.
- Expressões vagas, como "por agendamento" ou "ordem de chegada" sem complemento, não permitem inventar a modalidade. Consulte as fontes disponíveis; se o sistema informar modalidade não definida ou vínculo não resolvido, encaminhe à equipe para conferir. Não pergunte ao paciente como a clínica organiza o atendimento.
- Aceitar consultar vagas não escolhe um horário e não confirma uma reserva. Depois da escolha da vaga, apresente o resumo final com médico, atendimento, data, horário e modalidade corretos. O aceite desse resumo autoriza somente essa opção, mantendo as regras de cadastro e gravação. Sem vaga, siga HUM-04; sem registro no catálogo, siga FAT-04. Nunca substitua silenciosamente médico, dia ou horário.
Resultado esperado: escolha ou aceite → consulta real da agenda → opções com modalidade → escolha da vaga → resumo final → confirmação e operação autorizada, sem rodadas de confirmação repetidas. No atendimento sem pré-agendamento, a orientação de comparecimento substitui as etapas de reserva.`;
