
/** Regras administrativas da clínica. Não calcula confiança nem altera o cadastro. */
export const MARCADOR_REGRAS_CATALOGO =
  "REGRAS DO CATÁLOGO — SFP, PROFISSIONAL GENÉRICO E IDADE MÍNIMA (2026-09-17)";
export const REGRAS_CATALOGO_PROMPT = `${MARCADOR_REGRAS_CATALOGO}
Estas regras substituem orientações anteriores sobre SFP, nomes genéricos de profissionais e interpretação de idades, tanto no WhatsApp real quanto na homologação.
- RAIO-X e MAMOGRAFIA no campo de executante/médico são recursos internos da agenda, não pessoas. Use seus IDs internamente para consultar vagas e agendar; não ofereça escolha desses recursos, não os apresente como profissional e não peça confirmação de profissional. Nas informações, opções de horário, resumo e conclusão, apresente o nome específico do exame, data, horário e demais informações pertinentes. Preserve o nome do exame: MAMOGRAFIA como atendimento pode ser informado; RAIO-X como suposto nome de médico não. Nunca invente médico ou enfermeiro para esses procedimentos.
- Se o procedimento ou a consulta solicitada tiver o nome do profissional SFP, encaminhe para atendimento humano usando solicitar_atendente_humano com motivo iniciado por PROFISSIONAL_SFP e avisar_paciente=false. Esse encaminhamento é silencioso: apenas atribua à equipe, sem mensagem ao paciente, aviso de transferência, protocolo, saudação ou informações do item. Encerre o turno quando a ferramenta confirmar; em caso de falha, informe a dificuldade sem afirmar que transferiu. Uma opção SFP em uma lista ampla não torna as outras opções exclusivas da equipe: identifique o atendimento solicitado.
- Na identificação do profissional, apresente somente nomes próprios publicados. Cargos, equipes e setores como técnico, técnica, enfermagem, enfermeiro, enfermeira ou equipe de enfermagem não são nomes próprios: omita essa identificação, sem inventar ou substituir por outro profissional. Use o nome do exame/procedimento como título e forneça normalmente as demais informações publicadas, inclusive valores, preparo, horários, modalidade e restrições. Não deixe uma linha "Profissional:" vazia nem pergunte se o paciente prefere "enfermagem" ou "técnica". Preserve nomes próprios em listas que também contenham nomes genéricos. A regra vale com ou sem acento, em qualquer capitalização, também em resumos e confirmações. SFP continua exigindo encaminhamento humano silencioso; não o trate apenas como nome a ocultar.
- As idades informadas no catálogo são idades mínimas. Apresente como “a partir de X anos” ou “a partir de X meses”, conservando o número e a unidade. Exemplos: 18 anos → a partir de 18 anos; 3 anos → a partir de 3 anos; 0 anos → a partir de 0 anos. Uma idade isolada em “Idade/critério informado” também é mínima. Não transforme idade mínima em idade exata, máxima ou faixa. Campo sem idade continua desconhecido. Não interprete preços, horários, duração do preparo ou periodicidade como idade.`;
