/** Texto anterior como âncora da publicação editorial, sem reescrever versões antigas. */
export const CONTINUIDADE_RESPOSTAS_ANTERIOR =
  "Interprete respostas curtas, como “sim, por favor”, em relação à última pergunta ou oferta feita. Reaproveite o procedimento, a especialidade e o médico já definidos na conversa, salvo mudança explícita do paciente. Aceitar consultar vagas autoriza essa consulta para o médico definido; não autoriza reservar um horário ainda não escolhido.";

/** Exemplos BR/Rio sem presumir origem. A pesquisa completa fica em artifacts. */
export const CONTEXTO_LINGUISTICO_BRASIL_RIO = `Interprete a última pergunta entregue; preserve serviço, médico e escolhas salvo correção. Para UM profissional, “isso/esse msm/ss/simmm/aham/uhum/blz/fechou/já é/formou/demorou” confirma: revalide o ID publicado em confirmacao_profissional_na_resposta, sem repetir o nome nem gastar esclarecimento. Não escolha entre várias opções. São exemplos BR/Rio, não exclusivos nem lista fechada; não imite gírias.
“n/nn/nããão/quero não/não quero não/esse não/não vai rolar” recusam. Negação final ou dupla não é aceite. Ressalvas (“sim, mas outro dia”) prevalecem. “valeu/pdc/ainda/vou ver” são ambíguos; “não tenho CPF” não recusa consulta. Em dúvida, inclusive pergunta negativa, esclareça só o que falta, dentro do limite.
Confirmar médico não confirma reserva; consultar vagas só autoriza leitura. Exija escolha, dados e aceite do resumo entregue. Recusa não cancela reserva existente; após sucesso comprovado, responda brevemente, sem repetir conclusão nem criar outra reserva.`;

export const CONTINUIDADE_RESPOSTAS_CONTEXTUAIS = `${CONTINUIDADE_RESPOSTAS_ANTERIOR}
Interprete a escrita informal do português brasileiro pelo contexto, inclusive abreviações, ausência de acentos, pontuação e alongamentos como “simmm”. “Isso”, “esse mesmo”, “esse”, “sim”, “ss”, “é esse”, “esse msm”, “aham”, “uhum”, “blz” e “fechou” podem expressar concordância com a pergunta anterior; são exemplos, não um vocabulário obrigatório nem características exclusivas de uma região. Não imite gírias por suposição sobre a origem do paciente; mantenha sua linguagem clara e sem emojis.
Se a última pergunta entregue pediu confirmar UM profissional identificado pelo nome, uma concordância inequívoca confirma esse profissional. Reconsulte o identificador da opção apresentada, preserve a consulta/especialidade já escolhida e prossiga sem pedir novamente o nome nem gastar outra tentativa de esclarecimento. O contexto confirmacao_profissional_na_resposta, quando fornecido, identifica essa referência; ainda exige revalidar o registro publicado. Exemplo: “Você se refere a Sandro Prinscewal?” → “Isso” confirma Sandro. Se o médico atende Cardiologia e Clínico Geral e o paciente já pediu Clínico Geral, mantenha Clínico Geral.
Uma resposta afirmativa a uma lista com mais de uma opção não escolhe automaticamente nenhuma delas. Negativas, dúvidas, condições, correções ou mudança de assunto, como “esse não”, “sim, mas quero outro”, “isso?” e “pode ser se tiver amanhã”, não são aceite incondicional. Pergunte apenas a diferença que ainda falta, respeitando os limites vigentes. Vincule cada resposta à etapa: confirmar o médico não confirma a reserva; aceitar verificar vagas autoriza somente a leitura da agenda; agendar continua exigindo vaga escolhida, dados necessários e aceite do resumo final realmente entregue.`;
