/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppRecepcaoRouteImport } from './routes/_authenticated/app.recepcao'
import { Route as AuthenticatedAppRateioRouteImport } from './routes/_authenticated/app.rateio'
import { Route as AuthenticatedAppMedicosRouteImport } from './routes/_authenticated/app.medicos'
import { Route as AuthenticatedAppEquipeRouteImport } from './routes/_authenticated/app.equipe'
import { Route as AuthenticatedAppClinicasRouteImport } from './routes/_authenticated/app.clinicas'

const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRecepcaoRoute =
  AuthenticatedAppRecepcaoRouteImport.update({
    id: '/recepcao',
    path: '/recepcao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRateioRoute = AuthenticatedAppRateioRouteImport.update({
  id: '/rateio',
  path: '/rateio',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMedicosRoute = AuthenticatedAppMedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEquipeRoute = AuthenticatedAppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClinicasRoute =
  AuthenticatedAppClinicasRouteImport.update({
    id: '/clinicas',
    path: '/clinicas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/signup': typeof SignupRoute
  '/totem': typeof TotemRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/clinicas': typeof AuthenticatedAppClinicasRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/medicos': typeof AuthenticatedAppMedicosRoute
  '/app/rateio': typeof AuthenticatedAppRateioRoute
  '/app/recepcao': typeof AuthenticatedAppRecepcaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/signup': typeof SignupRoute
  '/totem': typeof TotemRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/clinicas': typeof AuthenticatedAppClinicasRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/medicos': typeof AuthenticatedAppMedicosRoute
  '/app/rateio': typeof AuthenticatedAppRateioRoute
  '/app/recepcao': typeof AuthenticatedAppRecepcaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/signup': typeof SignupRoute
  '/totem': typeof TotemRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/clinicas': typeof AuthenticatedAppClinicasRoute
  '/_authenticated/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/_authenticated/app/medicos': typeof AuthenticatedAppMedicosRoute
  '/_authenticated/app/rateio': typeof AuthenticatedAppRateioRoute
  '/_authenticated/app/recepcao': typeof AuthenticatedAppRecepcaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/painel'
    | '/signup'
    | '/totem'
    | '/app'
    | '/app/clinicas'
    | '/app/equipe'
    | '/app/medicos'
    | '/app/rateio'
    | '/app/recepcao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/painel'
    | '/signup'
    | '/totem'
    | '/app'
    | '/app/clinicas'
    | '/app/equipe'
    | '/app/medicos'
    | '/app/rateio'
    | '/app/recepcao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/painel'
    | '/signup'
    | '/totem'
    | '/_authenticated/app'
    | '/_authenticated/app/clinicas'
    | '/_authenticated/app/equipe'
    | '/_authenticated/app/medicos'
    | '/_authenticated/app/rateio'
    | '/_authenticated/app/recepcao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  SignupRoute: typeof SignupRoute
  TotemRoute: typeof TotemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/recepcao': {
      id: '/_authenticated/app/recepcao'
      path: '/recepcao'
      fullPath: '/app/recepcao'
      preLoaderRoute: typeof AuthenticatedAppRecepcaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rateio': {
      id: '/_authenticated/app/rateio'
      path: '/rateio'
      fullPath: '/app/rateio'
      preLoaderRoute: typeof AuthenticatedAppRateioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/medicos': {
      id: '/_authenticated/app/medicos'
      path: '/medicos'
      fullPath: '/app/medicos'
      preLoaderRoute: typeof AuthenticatedAppMedicosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/equipe': {
      id: '/_authenticated/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AuthenticatedAppEquipeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clinicas': {
      id: '/_authenticated/app/clinicas'
      path: '/clinicas'
      fullPath: '/app/clinicas'
      preLoaderRoute: typeof AuthenticatedAppClinicasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppClinicasRoute: typeof AuthenticatedAppClinicasRoute
  AuthenticatedAppEquipeRoute: typeof AuthenticatedAppEquipeRoute
  AuthenticatedAppMedicosRoute: typeof AuthenticatedAppMedicosRoute
  AuthenticatedAppRateioRoute: typeof AuthenticatedAppRateioRoute
  AuthenticatedAppRecepcaoRoute: typeof AuthenticatedAppRecepcaoRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppClinicasRoute: AuthenticatedAppClinicasRoute,
  AuthenticatedAppEquipeRoute: AuthenticatedAppEquipeRoute,
  AuthenticatedAppMedicosRoute: AuthenticatedAppMedicosRoute,
  AuthenticatedAppRateioRoute: AuthenticatedAppRateioRoute,
  AuthenticatedAppRecepcaoRoute: AuthenticatedAppRecepcaoRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  SignupRoute: SignupRoute,
  TotemRoute: TotemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
