/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacienteConsultasRouteImport } from './routes/paciente.consultas'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppRecepcaoRouteImport } from './routes/_authenticated/app.recepcao'
import { Route as AuthenticatedAppRateioRouteImport } from './routes/_authenticated/app.rateio'
import { Route as AuthenticatedAppProntuariosRouteImport } from './routes/_authenticated/app.prontuarios'
import { Route as AuthenticatedAppProcedimentosRouteImport } from './routes/_authenticated/app.procedimentos'
import { Route as AuthenticatedAppNinaRouteImport } from './routes/_authenticated/app.nina'
import { Route as AuthenticatedAppNfseRouteImport } from './routes/_authenticated/app.nfse'
import { Route as AuthenticatedAppModelosDocumentosRouteImport } from './routes/_authenticated/app.modelos-documentos'
import { Route as AuthenticatedAppMedicosRouteImport } from './routes/_authenticated/app.medicos'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppEstoqueRouteImport } from './routes/_authenticated/app.estoque'
import { Route as AuthenticatedAppEspecialidadesRouteImport } from './routes/_authenticated/app.especialidades'
import { Route as AuthenticatedAppEquipeRouteImport } from './routes/_authenticated/app.equipe'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app.documentos'
import { Route as AuthenticatedAppDisponibilidadesRouteImport } from './routes/_authenticated/app.disponibilidades'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/app.crm'
import { Route as AuthenticatedAppConsultaRapidaRouteImport } from './routes/_authenticated/app.consulta-rapida'
import { Route as AuthenticatedAppClinicasRouteImport } from './routes/_authenticated/app.clinicas'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app.clientes'
import { Route as AuthenticatedAppCampanhasRouteImport } from './routes/_authenticated/app.campanhas'
import { Route as AuthenticatedAppBoletosRouteImport } from './routes/_authenticated/app.boletos'
import { Route as AuthenticatedAppAnamnesesRouteImport } from './routes/_authenticated/app.anamneses'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppFinanceiroIndexRouteImport } from './routes/_authenticated/app.financeiro.index'
import { Route as AuthenticatedAppFinanceiroRelatoriosRouteImport } from './routes/_authenticated/app.financeiro.relatorios'
import { Route as AuthenticatedAppFinanceiroRegrasIaRouteImport } from './routes/_authenticated/app.financeiro.regras-ia'
import { Route as AuthenticatedAppFinanceiroNotasRouteImport } from './routes/_authenticated/app.financeiro.notas'
import { Route as AuthenticatedAppFinanceiroMovimentoRouteImport } from './routes/_authenticated/app.financeiro.movimento'
import { Route as AuthenticatedAppFinanceiroLembretesRouteImport } from './routes/_authenticated/app.financeiro.lembretes'
import { Route as AuthenticatedAppFinanceiroEstatisticasRouteImport } from './routes/_authenticated/app.financeiro.estatisticas'
import { Route as AuthenticatedAppFinanceiroEmpresasRouteImport } from './routes/_authenticated/app.financeiro.empresas'
import { Route as AuthenticatedAppFinanceiroContasRouteImport } from './routes/_authenticated/app.financeiro.contas'
import { Route as AuthenticatedAppFinanceiroCategoriasRouteImport } from './routes/_authenticated/app.financeiro.categorias'
import { Route as AuthenticatedAppFinanceiroBiRouteImport } from './routes/_authenticated/app.financeiro.bi'
import { Route as AuthenticatedAppFinanceiroAtendimentosRouteImport } from './routes/_authenticated/app.financeiro.atendimentos'
import { Route as AuthenticatedAppFinanceiroAnaliticoRouteImport } from './routes/_authenticated/app.financeiro.analitico'
import { Route as AuthenticatedAppFinanceiroAlertasRouteImport } from './routes/_authenticated/app.financeiro.alertas'

const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteConsultasRoute = PacienteConsultasRouteImport.update({
  id: '/paciente/consultas',
  path: '/paciente/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRecepcaoRoute =
  AuthenticatedAppRecepcaoRouteImport.update({
    id: '/recepcao',
    path: '/recepcao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRateioRoute = AuthenticatedAppRateioRouteImport.update({
  id: '/rateio',
  path: '/rateio',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProntuariosRoute =
  AuthenticatedAppProntuariosRouteImport.update({
    id: '/prontuarios',
    path: '/prontuarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProcedimentosRoute =
  AuthenticatedAppProcedimentosRouteImport.update({
    id: '/procedimentos',
    path: '/procedimentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNinaRoute = AuthenticatedAppNinaRouteImport.update({
  id: '/nina',
  path: '/nina',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNfseRoute = AuthenticatedAppNfseRouteImport.update({
  id: '/nfse',
  path: '/nfse',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModelosDocumentosRoute =
  AuthenticatedAppModelosDocumentosRouteImport.update({
    id: '/modelos-documentos',
    path: '/modelos-documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMedicosRoute = AuthenticatedAppMedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEstoqueRoute = AuthenticatedAppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEspecialidadesRoute =
  AuthenticatedAppEspecialidadesRouteImport.update({
    id: '/especialidades',
    path: '/especialidades',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEquipeRoute = AuthenticatedAppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDisponibilidadesRoute =
  AuthenticatedAppDisponibilidadesRouteImport.update({
    id: '/disponibilidades',
    path: '/disponibilidades',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConsultaRapidaRoute =
  AuthenticatedAppConsultaRapidaRouteImport.update({
    id: '/consulta-rapida',
    path: '/consulta-rapida',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClinicasRoute =
  AuthenticatedAppClinicasRouteImport.update({
    id: '/clinicas',
    path: '/clinicas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampanhasRoute =
  AuthenticatedAppCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBoletosRoute = AuthenticatedAppBoletosRouteImport.update({
  id: '/boletos',
  path: '/boletos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnamnesesRoute =
  AuthenticatedAppAnamnesesRouteImport.update({
    id: '/anamneses',
    path: '/anamneses',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFinanceiroIndexRoute =
  AuthenticatedAppFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroRelatoriosRoute =
  AuthenticatedAppFinanceiroRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroRegrasIaRoute =
  AuthenticatedAppFinanceiroRegrasIaRouteImport.update({
    id: '/regras-ia',
    path: '/regras-ia',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroNotasRoute =
  AuthenticatedAppFinanceiroNotasRouteImport.update({
    id: '/notas',
    path: '/notas',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroMovimentoRoute =
  AuthenticatedAppFinanceiroMovimentoRouteImport.update({
    id: '/movimento',
    path: '/movimento',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroLembretesRoute =
  AuthenticatedAppFinanceiroLembretesRouteImport.update({
    id: '/lembretes',
    path: '/lembretes',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroEstatisticasRoute =
  AuthenticatedAppFinanceiroEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroEmpresasRoute =
  AuthenticatedAppFinanceiroEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroContasRoute =
  AuthenticatedAppFinanceiroContasRouteImport.update({
    id: '/contas',
    path: '/contas',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroCategoriasRoute =
  AuthenticatedAppFinanceiroCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroBiRoute =
  AuthenticatedAppFinanceiroBiRouteImport.update({
    id: '/bi',
    path: '/bi',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroAtendimentosRoute =
  AuthenticatedAppFinanceiroAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroAnaliticoRoute =
  AuthenticatedAppFinanceiroAnaliticoRouteImport.update({
    id: '/analitico',
    path: '/analitico',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroAlertasRoute =
  AuthenticatedAppFinanceiroAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/signup': typeof SignupRoute
  '/totem': typeof TotemRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/paciente/consultas': typeof PacienteConsultasRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/anamneses': typeof AuthenticatedAppAnamnesesRoute
  '/app/boletos': typeof AuthenticatedAppBoletosRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/clinicas': typeof AuthenticatedAppClinicasRoute
  '/app/consulta-rapida': typeof AuthenticatedAppConsultaRapidaRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/disponibilidades': typeof AuthenticatedAppDisponibilidadesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/especialidades': typeof AuthenticatedAppEspecialidadesRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRouteWithChildren
  '/app/medicos': typeof AuthenticatedAppMedicosRoute
  '/app/modelos-documentos': typeof AuthenticatedAppModelosDocumentosRoute
  '/app/nfse': typeof AuthenticatedAppNfseRoute
  '/app/nina': typeof AuthenticatedAppNinaRoute
  '/app/procedimentos': typeof AuthenticatedAppProcedimentosRoute
  '/app/prontuarios': typeof AuthenticatedAppProntuariosRoute
  '/app/rateio': typeof AuthenticatedAppRateioRoute
  '/app/recepcao': typeof AuthenticatedAppRecepcaoRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/financeiro/alertas': typeof AuthenticatedAppFinanceiroAlertasRoute
  '/app/financeiro/analitico': typeof AuthenticatedAppFinanceiroAnaliticoRoute
  '/app/financeiro/atendimentos': typeof AuthenticatedAppFinanceiroAtendimentosRoute
  '/app/financeiro/bi': typeof AuthenticatedAppFinanceiroBiRoute
  '/app/financeiro/categorias': typeof AuthenticatedAppFinanceiroCategoriasRoute
  '/app/financeiro/contas': typeof AuthenticatedAppFinanceiroContasRoute
  '/app/financeiro/empresas': typeof AuthenticatedAppFinanceiroEmpresasRoute
  '/app/financeiro/estatisticas': typeof AuthenticatedAppFinanceiroEstatisticasRoute
  '/app/financeiro/lembretes': typeof AuthenticatedAppFinanceiroLembretesRoute
  '/app/financeiro/movimento': typeof AuthenticatedAppFinanceiroMovimentoRoute
  '/app/financeiro/notas': typeof AuthenticatedAppFinanceiroNotasRoute
  '/app/financeiro/regras-ia': typeof AuthenticatedAppFinanceiroRegrasIaRoute
  '/app/financeiro/relatorios': typeof AuthenticatedAppFinanceiroRelatoriosRoute
  '/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/signup': typeof SignupRoute
  '/totem': typeof TotemRoute
  '/p/$token': typeof PTokenRoute
  '/paciente/consultas': typeof PacienteConsultasRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/anamneses': typeof AuthenticatedAppAnamnesesRoute
  '/app/boletos': typeof AuthenticatedAppBoletosRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/clinicas': typeof AuthenticatedAppClinicasRoute
  '/app/consulta-rapida': typeof AuthenticatedAppConsultaRapidaRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/disponibilidades': typeof AuthenticatedAppDisponibilidadesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/app/especialidades': typeof AuthenticatedAppEspecialidadesRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/medicos': typeof AuthenticatedAppMedicosRoute
  '/app/modelos-documentos': typeof AuthenticatedAppModelosDocumentosRoute
  '/app/nfse': typeof AuthenticatedAppNfseRoute
  '/app/nina': typeof AuthenticatedAppNinaRoute
  '/app/procedimentos': typeof AuthenticatedAppProcedimentosRoute
  '/app/prontuarios': typeof AuthenticatedAppProntuariosRoute
  '/app/rateio': typeof AuthenticatedAppRateioRoute
  '/app/recepcao': typeof AuthenticatedAppRecepcaoRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/financeiro/alertas': typeof AuthenticatedAppFinanceiroAlertasRoute
  '/app/financeiro/analitico': typeof AuthenticatedAppFinanceiroAnaliticoRoute
  '/app/financeiro/atendimentos': typeof AuthenticatedAppFinanceiroAtendimentosRoute
  '/app/financeiro/bi': typeof AuthenticatedAppFinanceiroBiRoute
  '/app/financeiro/categorias': typeof AuthenticatedAppFinanceiroCategoriasRoute
  '/app/financeiro/contas': typeof AuthenticatedAppFinanceiroContasRoute
  '/app/financeiro/empresas': typeof AuthenticatedAppFinanceiroEmpresasRoute
  '/app/financeiro/estatisticas': typeof AuthenticatedAppFinanceiroEstatisticasRoute
  '/app/financeiro/lembretes': typeof AuthenticatedAppFinanceiroLembretesRoute
  '/app/financeiro/movimento': typeof AuthenticatedAppFinanceiroMovimentoRoute
  '/app/financeiro/notas': typeof AuthenticatedAppFinanceiroNotasRoute
  '/app/financeiro/regras-ia': typeof AuthenticatedAppFinanceiroRegrasIaRoute
  '/app/financeiro/relatorios': typeof AuthenticatedAppFinanceiroRelatoriosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/signup': typeof SignupRoute
  '/totem': typeof TotemRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/paciente/consultas': typeof PacienteConsultasRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/anamneses': typeof AuthenticatedAppAnamnesesRoute
  '/_authenticated/app/boletos': typeof AuthenticatedAppBoletosRoute
  '/_authenticated/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/clinicas': typeof AuthenticatedAppClinicasRoute
  '/_authenticated/app/consulta-rapida': typeof AuthenticatedAppConsultaRapidaRoute
  '/_authenticated/app/crm': typeof AuthenticatedAppCrmRoute
  '/_authenticated/app/disponibilidades': typeof AuthenticatedAppDisponibilidadesRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/equipe': typeof AuthenticatedAppEquipeRoute
  '/_authenticated/app/especialidades': typeof AuthenticatedAppEspecialidadesRoute
  '/_authenticated/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRouteWithChildren
  '/_authenticated/app/medicos': typeof AuthenticatedAppMedicosRoute
  '/_authenticated/app/modelos-documentos': typeof AuthenticatedAppModelosDocumentosRoute
  '/_authenticated/app/nfse': typeof AuthenticatedAppNfseRoute
  '/_authenticated/app/nina': typeof AuthenticatedAppNinaRoute
  '/_authenticated/app/procedimentos': typeof AuthenticatedAppProcedimentosRoute
  '/_authenticated/app/prontuarios': typeof AuthenticatedAppProntuariosRoute
  '/_authenticated/app/rateio': typeof AuthenticatedAppRateioRoute
  '/_authenticated/app/recepcao': typeof AuthenticatedAppRecepcaoRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/financeiro/alertas': typeof AuthenticatedAppFinanceiroAlertasRoute
  '/_authenticated/app/financeiro/analitico': typeof AuthenticatedAppFinanceiroAnaliticoRoute
  '/_authenticated/app/financeiro/atendimentos': typeof AuthenticatedAppFinanceiroAtendimentosRoute
  '/_authenticated/app/financeiro/bi': typeof AuthenticatedAppFinanceiroBiRoute
  '/_authenticated/app/financeiro/categorias': typeof AuthenticatedAppFinanceiroCategoriasRoute
  '/_authenticated/app/financeiro/contas': typeof AuthenticatedAppFinanceiroContasRoute
  '/_authenticated/app/financeiro/empresas': typeof AuthenticatedAppFinanceiroEmpresasRoute
  '/_authenticated/app/financeiro/estatisticas': typeof AuthenticatedAppFinanceiroEstatisticasRoute
  '/_authenticated/app/financeiro/lembretes': typeof AuthenticatedAppFinanceiroLembretesRoute
  '/_authenticated/app/financeiro/movimento': typeof AuthenticatedAppFinanceiroMovimentoRoute
  '/_authenticated/app/financeiro/notas': typeof AuthenticatedAppFinanceiroNotasRoute
  '/_authenticated/app/financeiro/regras-ia': typeof AuthenticatedAppFinanceiroRegrasIaRoute
  '/_authenticated/app/financeiro/relatorios': typeof AuthenticatedAppFinanceiroRelatoriosRoute
  '/_authenticated/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/painel'
    | '/signup'
    | '/totem'
    | '/app'
    | '/p/$token'
    | '/paciente/consultas'
    | '/app/agenda'
    | '/app/anamneses'
    | '/app/boletos'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/clinicas'
    | '/app/consulta-rapida'
    | '/app/crm'
    | '/app/disponibilidades'
    | '/app/documentos'
    | '/app/equipe'
    | '/app/especialidades'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/medicos'
    | '/app/modelos-documentos'
    | '/app/nfse'
    | '/app/nina'
    | '/app/procedimentos'
    | '/app/prontuarios'
    | '/app/rateio'
    | '/app/recepcao'
    | '/app/'
    | '/app/financeiro/alertas'
    | '/app/financeiro/analitico'
    | '/app/financeiro/atendimentos'
    | '/app/financeiro/bi'
    | '/app/financeiro/categorias'
    | '/app/financeiro/contas'
    | '/app/financeiro/empresas'
    | '/app/financeiro/estatisticas'
    | '/app/financeiro/lembretes'
    | '/app/financeiro/movimento'
    | '/app/financeiro/notas'
    | '/app/financeiro/regras-ia'
    | '/app/financeiro/relatorios'
    | '/app/financeiro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/painel'
    | '/signup'
    | '/totem'
    | '/p/$token'
    | '/paciente/consultas'
    | '/app/agenda'
    | '/app/anamneses'
    | '/app/boletos'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/clinicas'
    | '/app/consulta-rapida'
    | '/app/crm'
    | '/app/disponibilidades'
    | '/app/documentos'
    | '/app/equipe'
    | '/app/especialidades'
    | '/app/estoque'
    | '/app/medicos'
    | '/app/modelos-documentos'
    | '/app/nfse'
    | '/app/nina'
    | '/app/procedimentos'
    | '/app/prontuarios'
    | '/app/rateio'
    | '/app/recepcao'
    | '/app'
    | '/app/financeiro/alertas'
    | '/app/financeiro/analitico'
    | '/app/financeiro/atendimentos'
    | '/app/financeiro/bi'
    | '/app/financeiro/categorias'
    | '/app/financeiro/contas'
    | '/app/financeiro/empresas'
    | '/app/financeiro/estatisticas'
    | '/app/financeiro/lembretes'
    | '/app/financeiro/movimento'
    | '/app/financeiro/notas'
    | '/app/financeiro/regras-ia'
    | '/app/financeiro/relatorios'
    | '/app/financeiro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/painel'
    | '/signup'
    | '/totem'
    | '/_authenticated/app'
    | '/p/$token'
    | '/paciente/consultas'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/anamneses'
    | '/_authenticated/app/boletos'
    | '/_authenticated/app/campanhas'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/clinicas'
    | '/_authenticated/app/consulta-rapida'
    | '/_authenticated/app/crm'
    | '/_authenticated/app/disponibilidades'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/equipe'
    | '/_authenticated/app/especialidades'
    | '/_authenticated/app/estoque'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/medicos'
    | '/_authenticated/app/modelos-documentos'
    | '/_authenticated/app/nfse'
    | '/_authenticated/app/nina'
    | '/_authenticated/app/procedimentos'
    | '/_authenticated/app/prontuarios'
    | '/_authenticated/app/rateio'
    | '/_authenticated/app/recepcao'
    | '/_authenticated/app/'
    | '/_authenticated/app/financeiro/alertas'
    | '/_authenticated/app/financeiro/analitico'
    | '/_authenticated/app/financeiro/atendimentos'
    | '/_authenticated/app/financeiro/bi'
    | '/_authenticated/app/financeiro/categorias'
    | '/_authenticated/app/financeiro/contas'
    | '/_authenticated/app/financeiro/empresas'
    | '/_authenticated/app/financeiro/estatisticas'
    | '/_authenticated/app/financeiro/lembretes'
    | '/_authenticated/app/financeiro/movimento'
    | '/_authenticated/app/financeiro/notas'
    | '/_authenticated/app/financeiro/regras-ia'
    | '/_authenticated/app/financeiro/relatorios'
    | '/_authenticated/app/financeiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  SignupRoute: typeof SignupRoute
  TotemRoute: typeof TotemRoute
  PTokenRoute: typeof PTokenRoute
  PacienteConsultasRoute: typeof PacienteConsultasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/consultas': {
      id: '/paciente/consultas'
      path: '/paciente/consultas'
      fullPath: '/paciente/consultas'
      preLoaderRoute: typeof PacienteConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/recepcao': {
      id: '/_authenticated/app/recepcao'
      path: '/recepcao'
      fullPath: '/app/recepcao'
      preLoaderRoute: typeof AuthenticatedAppRecepcaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rateio': {
      id: '/_authenticated/app/rateio'
      path: '/rateio'
      fullPath: '/app/rateio'
      preLoaderRoute: typeof AuthenticatedAppRateioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prontuarios': {
      id: '/_authenticated/app/prontuarios'
      path: '/prontuarios'
      fullPath: '/app/prontuarios'
      preLoaderRoute: typeof AuthenticatedAppProntuariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/procedimentos': {
      id: '/_authenticated/app/procedimentos'
      path: '/procedimentos'
      fullPath: '/app/procedimentos'
      preLoaderRoute: typeof AuthenticatedAppProcedimentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nina': {
      id: '/_authenticated/app/nina'
      path: '/nina'
      fullPath: '/app/nina'
      preLoaderRoute: typeof AuthenticatedAppNinaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nfse': {
      id: '/_authenticated/app/nfse'
      path: '/nfse'
      fullPath: '/app/nfse'
      preLoaderRoute: typeof AuthenticatedAppNfseRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/modelos-documentos': {
      id: '/_authenticated/app/modelos-documentos'
      path: '/modelos-documentos'
      fullPath: '/app/modelos-documentos'
      preLoaderRoute: typeof AuthenticatedAppModelosDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/medicos': {
      id: '/_authenticated/app/medicos'
      path: '/medicos'
      fullPath: '/app/medicos'
      preLoaderRoute: typeof AuthenticatedAppMedicosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/estoque': {
      id: '/_authenticated/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AuthenticatedAppEstoqueRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/especialidades': {
      id: '/_authenticated/app/especialidades'
      path: '/especialidades'
      fullPath: '/app/especialidades'
      preLoaderRoute: typeof AuthenticatedAppEspecialidadesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/equipe': {
      id: '/_authenticated/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AuthenticatedAppEquipeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/disponibilidades': {
      id: '/_authenticated/app/disponibilidades'
      path: '/disponibilidades'
      fullPath: '/app/disponibilidades'
      preLoaderRoute: typeof AuthenticatedAppDisponibilidadesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/crm': {
      id: '/_authenticated/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/consulta-rapida': {
      id: '/_authenticated/app/consulta-rapida'
      path: '/consulta-rapida'
      fullPath: '/app/consulta-rapida'
      preLoaderRoute: typeof AuthenticatedAppConsultaRapidaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clinicas': {
      id: '/_authenticated/app/clinicas'
      path: '/clinicas'
      fullPath: '/app/clinicas'
      preLoaderRoute: typeof AuthenticatedAppClinicasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campanhas': {
      id: '/_authenticated/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AuthenticatedAppCampanhasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/boletos': {
      id: '/_authenticated/app/boletos'
      path: '/boletos'
      fullPath: '/app/boletos'
      preLoaderRoute: typeof AuthenticatedAppBoletosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/anamneses': {
      id: '/_authenticated/app/anamneses'
      path: '/anamneses'
      fullPath: '/app/anamneses'
      preLoaderRoute: typeof AuthenticatedAppAnamnesesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro/': {
      id: '/_authenticated/app/financeiro/'
      path: '/'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/relatorios': {
      id: '/_authenticated/app/financeiro/relatorios'
      path: '/relatorios'
      fullPath: '/app/financeiro/relatorios'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/regras-ia': {
      id: '/_authenticated/app/financeiro/regras-ia'
      path: '/regras-ia'
      fullPath: '/app/financeiro/regras-ia'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRegrasIaRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/notas': {
      id: '/_authenticated/app/financeiro/notas'
      path: '/notas'
      fullPath: '/app/financeiro/notas'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroNotasRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/movimento': {
      id: '/_authenticated/app/financeiro/movimento'
      path: '/movimento'
      fullPath: '/app/financeiro/movimento'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroMovimentoRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/lembretes': {
      id: '/_authenticated/app/financeiro/lembretes'
      path: '/lembretes'
      fullPath: '/app/financeiro/lembretes'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroLembretesRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/estatisticas': {
      id: '/_authenticated/app/financeiro/estatisticas'
      path: '/estatisticas'
      fullPath: '/app/financeiro/estatisticas'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroEstatisticasRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/empresas': {
      id: '/_authenticated/app/financeiro/empresas'
      path: '/empresas'
      fullPath: '/app/financeiro/empresas'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroEmpresasRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/contas': {
      id: '/_authenticated/app/financeiro/contas'
      path: '/contas'
      fullPath: '/app/financeiro/contas'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroContasRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/categorias': {
      id: '/_authenticated/app/financeiro/categorias'
      path: '/categorias'
      fullPath: '/app/financeiro/categorias'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroCategoriasRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/bi': {
      id: '/_authenticated/app/financeiro/bi'
      path: '/bi'
      fullPath: '/app/financeiro/bi'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroBiRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/atendimentos': {
      id: '/_authenticated/app/financeiro/atendimentos'
      path: '/atendimentos'
      fullPath: '/app/financeiro/atendimentos'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroAtendimentosRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/analitico': {
      id: '/_authenticated/app/financeiro/analitico'
      path: '/analitico'
      fullPath: '/app/financeiro/analitico'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroAnaliticoRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/alertas': {
      id: '/_authenticated/app/financeiro/alertas'
      path: '/alertas'
      fullPath: '/app/financeiro/alertas'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroAlertasRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
  }
}

interface AuthenticatedAppFinanceiroRouteChildren {
  AuthenticatedAppFinanceiroAlertasRoute: typeof AuthenticatedAppFinanceiroAlertasRoute
  AuthenticatedAppFinanceiroAnaliticoRoute: typeof AuthenticatedAppFinanceiroAnaliticoRoute
  AuthenticatedAppFinanceiroAtendimentosRoute: typeof AuthenticatedAppFinanceiroAtendimentosRoute
  AuthenticatedAppFinanceiroBiRoute: typeof AuthenticatedAppFinanceiroBiRoute
  AuthenticatedAppFinanceiroCategoriasRoute: typeof AuthenticatedAppFinanceiroCategoriasRoute
  AuthenticatedAppFinanceiroContasRoute: typeof AuthenticatedAppFinanceiroContasRoute
  AuthenticatedAppFinanceiroEmpresasRoute: typeof AuthenticatedAppFinanceiroEmpresasRoute
  AuthenticatedAppFinanceiroEstatisticasRoute: typeof AuthenticatedAppFinanceiroEstatisticasRoute
  AuthenticatedAppFinanceiroLembretesRoute: typeof AuthenticatedAppFinanceiroLembretesRoute
  AuthenticatedAppFinanceiroMovimentoRoute: typeof AuthenticatedAppFinanceiroMovimentoRoute
  AuthenticatedAppFinanceiroNotasRoute: typeof AuthenticatedAppFinanceiroNotasRoute
  AuthenticatedAppFinanceiroRegrasIaRoute: typeof AuthenticatedAppFinanceiroRegrasIaRoute
  AuthenticatedAppFinanceiroRelatoriosRoute: typeof AuthenticatedAppFinanceiroRelatoriosRoute
  AuthenticatedAppFinanceiroIndexRoute: typeof AuthenticatedAppFinanceiroIndexRoute
}

const AuthenticatedAppFinanceiroRouteChildren: AuthenticatedAppFinanceiroRouteChildren =
  {
    AuthenticatedAppFinanceiroAlertasRoute:
      AuthenticatedAppFinanceiroAlertasRoute,
    AuthenticatedAppFinanceiroAnaliticoRoute:
      AuthenticatedAppFinanceiroAnaliticoRoute,
    AuthenticatedAppFinanceiroAtendimentosRoute:
      AuthenticatedAppFinanceiroAtendimentosRoute,
    AuthenticatedAppFinanceiroBiRoute: AuthenticatedAppFinanceiroBiRoute,
    AuthenticatedAppFinanceiroCategoriasRoute:
      AuthenticatedAppFinanceiroCategoriasRoute,
    AuthenticatedAppFinanceiroContasRoute:
      AuthenticatedAppFinanceiroContasRoute,
    AuthenticatedAppFinanceiroEmpresasRoute:
      AuthenticatedAppFinanceiroEmpresasRoute,
    AuthenticatedAppFinanceiroEstatisticasRoute:
      AuthenticatedAppFinanceiroEstatisticasRoute,
    AuthenticatedAppFinanceiroLembretesRoute:
      AuthenticatedAppFinanceiroLembretesRoute,
    AuthenticatedAppFinanceiroMovimentoRoute:
      AuthenticatedAppFinanceiroMovimentoRoute,
    AuthenticatedAppFinanceiroNotasRoute: AuthenticatedAppFinanceiroNotasRoute,
    AuthenticatedAppFinanceiroRegrasIaRoute:
      AuthenticatedAppFinanceiroRegrasIaRoute,
    AuthenticatedAppFinanceiroRelatoriosRoute:
      AuthenticatedAppFinanceiroRelatoriosRoute,
    AuthenticatedAppFinanceiroIndexRoute: AuthenticatedAppFinanceiroIndexRoute,
  }

const AuthenticatedAppFinanceiroRouteWithChildren =
  AuthenticatedAppFinanceiroRoute._addFileChildren(
    AuthenticatedAppFinanceiroRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAnamnesesRoute: typeof AuthenticatedAppAnamnesesRoute
  AuthenticatedAppBoletosRoute: typeof AuthenticatedAppBoletosRoute
  AuthenticatedAppCampanhasRoute: typeof AuthenticatedAppCampanhasRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppClinicasRoute: typeof AuthenticatedAppClinicasRoute
  AuthenticatedAppConsultaRapidaRoute: typeof AuthenticatedAppConsultaRapidaRoute
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRoute
  AuthenticatedAppDisponibilidadesRoute: typeof AuthenticatedAppDisponibilidadesRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppEquipeRoute: typeof AuthenticatedAppEquipeRoute
  AuthenticatedAppEspecialidadesRoute: typeof AuthenticatedAppEspecialidadesRoute
  AuthenticatedAppEstoqueRoute: typeof AuthenticatedAppEstoqueRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRouteWithChildren
  AuthenticatedAppMedicosRoute: typeof AuthenticatedAppMedicosRoute
  AuthenticatedAppModelosDocumentosRoute: typeof AuthenticatedAppModelosDocumentosRoute
  AuthenticatedAppNfseRoute: typeof AuthenticatedAppNfseRoute
  AuthenticatedAppNinaRoute: typeof AuthenticatedAppNinaRoute
  AuthenticatedAppProcedimentosRoute: typeof AuthenticatedAppProcedimentosRoute
  AuthenticatedAppProntuariosRoute: typeof AuthenticatedAppProntuariosRoute
  AuthenticatedAppRateioRoute: typeof AuthenticatedAppRateioRoute
  AuthenticatedAppRecepcaoRoute: typeof AuthenticatedAppRecepcaoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAnamnesesRoute: AuthenticatedAppAnamnesesRoute,
  AuthenticatedAppBoletosRoute: AuthenticatedAppBoletosRoute,
  AuthenticatedAppCampanhasRoute: AuthenticatedAppCampanhasRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppClinicasRoute: AuthenticatedAppClinicasRoute,
  AuthenticatedAppConsultaRapidaRoute: AuthenticatedAppConsultaRapidaRoute,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRoute,
  AuthenticatedAppDisponibilidadesRoute: AuthenticatedAppDisponibilidadesRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppEquipeRoute: AuthenticatedAppEquipeRoute,
  AuthenticatedAppEspecialidadesRoute: AuthenticatedAppEspecialidadesRoute,
  AuthenticatedAppEstoqueRoute: AuthenticatedAppEstoqueRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRouteWithChildren,
  AuthenticatedAppMedicosRoute: AuthenticatedAppMedicosRoute,
  AuthenticatedAppModelosDocumentosRoute:
    AuthenticatedAppModelosDocumentosRoute,
  AuthenticatedAppNfseRoute: AuthenticatedAppNfseRoute,
  AuthenticatedAppNinaRoute: AuthenticatedAppNinaRoute,
  AuthenticatedAppProcedimentosRoute: AuthenticatedAppProcedimentosRoute,
  AuthenticatedAppProntuariosRoute: AuthenticatedAppProntuariosRoute,
  AuthenticatedAppRateioRoute: AuthenticatedAppRateioRoute,
  AuthenticatedAppRecepcaoRoute: AuthenticatedAppRecepcaoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  SignupRoute: SignupRoute,
  TotemRoute: TotemRoute,
  PTokenRoute: PTokenRoute,
  PacienteConsultasRoute: PacienteConsultasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
