-- Desabilita auditoria temporariamente para acelerar a operação em lote
SET session_replication_role = replica;

WITH alvo AS (
  SELECT id FROM public.medicos
  WHERE upper(nome) IN (
    'ADRIANA','ALESSANDRA','ANDREA DE LUCCA','ANDRESSA','ANIBAL FABIANO MARENGA',
    'ARMANDO','BARBARA OLIVEIRA','BENITES','BRUNA','CAMILA','CARLOS EDUARDO',
    'CARLOS FEIER','CARLOS FELIPE','CAROLINA','CARTAO CONSULTA','CARTAO CONSULTA + SEGURO',
    'CATARINA','CLAUDIA','CLAUDIA MADUREIRA','CLAUDIO','CONCEICAO','DANIEL','DAYANE',
    'DENISE','ELAIR','ENEIDA','FABIANA','FELIPE CESAR','FELIPE MOURA','FERNANDA',
    'FLAVIA VIEIRA','FRANCISCO','GUSTAVO CARNEVALE','GUSTAVO JARDIM RNM','GUSTAVO JARDIM TC',
    'GUSTAVO MAGALHAES','HUGO','IARMILA','IVAN','JOAO HELIO','JORGE RIBEIRO','JUNIOR',
    'KARINA','KARINA RUIZ CARDOSO DE OLIVEIRA','KATIA','KETLEN','LUCIO','MAICON',
    'MARCIA','MARCOS','MARGARETE','MARIA CONSUELO','MARIA DAS GRACAS','MARIANA',
    'MAURICIO','MICHELE DE ALMEIDA FERREIRA','MICHELLE MARTINS DUARTE DA COSTA',
    'MILTON','MONICA','OSCAR','PATRICIA','PAULO GUILHERME','PAULO ROBERTO','POLIANA',
    'PRISCILA ANA BRAGA DA SILVA ROCHA','QUEDIMA SOARES','RAFAEL',
    'RAIANI NIEDZIELSKI GOMES','RAISSA','RENATA RETONDE DOS REIS','RICARDO FELIPE',
    'SAMUEL JOSE','SERGIO NADER','TARCISIO','THALITA','THIAGO DE OLIVEIRA GUIMARAES',
    'VALERIA','VALERIA SILVEIRA LIMA','YASMIN'
  )
),
del_ag AS (
  DELETE FROM public.agendamentos WHERE medico_id IN (SELECT id FROM alvo) RETURNING 1
)
DELETE FROM public.medicos WHERE id IN (SELECT id FROM alvo);

SET session_replication_role = DEFAULT;